### ISSUE TITLE
Open Android Studio from a Flutter app project

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#1063]
Analogous to: https://github.com/flutter/flutter-intellij/issues/880

**Comment by pq** [comment]
See:

https://flutter.io/platform-plugins/#android-platform-code-javakt

for details on what to open.

**Comment by pq** [comment]
So this is turning out to be a tricky flow.  `flutter create` generates two IML files that appear promising (`android.iml` and `<project_name>_android.iml`) but simply asking AS to open one of them doesn't appear to work.

@skybrian: any thoughts on whether this is doable?

Our [docs](https://flutter.io/platform-plugins/#android-platform-code-javakt) detail a bunch of manual steps:

> Before editing the Android platform code in Android Studio, first make sure that the code has been built at least once (i.e., run the example app from IntelliJ, or in a terminal execute cd hello/example; flutter build apk).
> 
> Next,
> 
> Launch Android Studio
> Select ‘Import project’ in ‘Welcome to Android Studio’ dialog, or select ‘File > New > Import Project…’’ in the menu, and select the hello/example/android/build.gradle file.
> In the ‘Gradle Sync’ dialog, select ‘OK’.
> In the ‘Android Gradle Plugin Update’ dialog, select ‘Don’t remind me again for this project’.
> The Android platform code of your plugin is located in hello/java/com.yourcompany.hello/HelloPlugin.

Any way around the manual import?

**Comment by skybrian** [comment]
One possibility would be to go through the import process, see what files it generates and see if we can generate them instead, so the user can open the project instead of importing it. However, IntelliJ's Gradle integration is tricky; it automatically creates entire modules behind the scenes, based on the Gradle file. (Android Studio hides some of the complexity.)

Also, this would be another thing in the templates and we just had a discussion about that. (see: https://github.com/flutter/flutter/pull/10429)

**Comment by mofada** [comment]
It is grey
![Open in andorid](https://user-images.githubusercontent.com/22286246/63990773-d6cdab00-cb17-11e9-98d7-dc5ce55b0482.png)
