### ISSUE TITLE
Produce more output in the IJ terminal during builds

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#1068]
We have had a number of issues recently where flutter builds on both android and ios slowed down due to several "environment" issues (e.g., gradle setup, network throttling, Pod install). When running in the terminal it's somewhat clear where the slowdown is, and that nothing is "hung" as you get a progress spinner. In IntelliJ it's harder as 1) there is little terminal feedback, and 2) you may miss the progress indicator in the IJ window chrome.

I'd like to propose we simply print the same status to the IJ terminal that `flutter run` / `flutter build` prints to the terminal (incl. the `/` spinner for indeterminate progress).

**Comment by devoncarew** [comment]
Printing the progress text sounds like a good thing to experiment with.

Whenever the cli shows a spinner, IntelliJ shows an indeterminate progress bar (in the status line or in the editor, depending on a user preference). Sounds like the progress bar is harder to notice. I'm of two minds about adding a text spinner, since that seems appropriate for a CLI, but low-fidelity for an IDE (w/ existing progress conventions).

**Comment by devoncarew** [comment]
We're doing most of this now - we're printing the progress messages (in addition to showing the IntelliJ progress UI), and now have a setting to effectively enable `flutter tun -v` (which should help diagnose issues where we're not making progress when running apps).
