### ISSUE TITLE
when running a flutter app, we're breaking at exceptions

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1164]
The run mode likely shouldn't break - the users can use debug mode for that.

(/cc @alextekartik)

**Comment by alextekartik** [comment]
(thanks Devon for opening the issue)
I have not found a small snippet to reproduce the issue. So here is the best step I know. 

Get and run the example of [sqflite](https://github.com/tekartik/sqflite)

Run the application using `flutter run`, choose _Open Tests_. All the tests are executed fine (green check mark).

Now run (not debug) the same application from Intellij. It breaks at `throw new ArgumentError(...)`. However I can resume the program (it breaks at other `throw`) until it passes and the app continues to work fine.

Maybe it is due to my code (I agree the throws are deep but it is on purpose!). But the throws are expected and caught by the app.

I have reproduce the issue on Ubuntu and on Mac, using WebStrom 2017.1, running the app on Android (and iOS I think), Tools Dart version 1.24.0-dev.6.7

**Comment by devoncarew** [comment]
Elevating the priority of this issue. In 'run' mode, users don't have the same UI available to them to make it easy to discover how to resume their application. In addition, the use of the Inspector makes it more likely that the user will break on an exception.

**Comment by devoncarew** [comment]
Fixing this is complicated by the fact that the code to handle break-on-exceptions is in the Dart plugin, and if we tried to adjust the VM's break on exceptions behavior from the flutter plugin it would be racy.

A meta-solution would set break-on-exceptions to none during a run for each isolate (or in other words, key off the XDebugSession.areBreakpointsMuted() value).

/cc @alexander-doroshko - we may need coordinated changes to the Dart plugin here. I don't know exactly what a solution would look like but am happy to discuss.

**Comment by alexander-doroshko** [comment]
Do you use `FlutterDebugProcess` even when *Running* the app? Then override `getBreakpointHandlers()` and return empty array when running.

**Comment by devoncarew** [comment]
> Do you use FlutterDebugProcess even when Running the app?

we do (I forget the actual reason, but could look it up)

> Then override getBreakpointHandlers() and return empty array when running.

If that's a solution it's something we could readily implement in the Flutter plugin.

**Comment by alexander-doroshko** [comment]
However, I might be wrong. You already do override `getBreakpointHandlers()` in `DartVmServiceDebugProcess`. 

Well, anyway I think you can fix it in the Flutter plugin. Track how the execution comes to the `vmServiceWrapper.setExceptionPauseMode()` call.

**Comment by alexander-doroshko** [comment]
Looks like this place is `VmServiceWrapper#handleIsolate` and it is out of direct control of the Flutter plugin. As a dirty workaround you may `DartExceptionBreakpointHandler.getDefaultExceptionBreakpoint().setEnabled(false)` while Flutter app is in progress. Need to think of a better fix.

**Comment by devoncarew** [comment]
This is fixed on the Dart plugin, and the fix will work it's way downstream to the stable channels.
