### ISSUE TITLE
what missing async does to intellij code formatter

### ISSUE THREAD

**Issue by yjbanov** [flutter/flutter-intellij#1351]
Below I'm trying to close the function body using a `}`. Unfortunately, I forgot the `async` in the declaration. As a result, Intellij goes crazy.

![what missing async does to intellij](https://user-images.githubusercontent.com/211513/30822503-d772369e-a1dd-11e7-9ff6-ef14fef8cc5c.gif)

**Comment by devoncarew** [comment]
This is just as you're typing the closing `}`, right (not on a save w/ auto-dartfmt on save on)?

/cc @alexander-doroshko

**Comment by yjbanov** [comment]
Yep. One key stroke, the `}`.

**Comment by alexander-doroshko** [comment]
Block reformatting is happening because you've enabled `Reformat block on typing '}'` option in File | Settings | Editor | General | Smart Keys (this option is disabled by default).
I agree that missing `async` should not cause such an unfortunate result. Worth filing an issue in [JetBrains issue tracker](https://youtrack.jetbrains.com/issues/WEB).

**Comment by yjbanov** [comment]
Filed https://youtrack.jetbrains.com/issue/WEB-28954

Disabling block reformatting helped. Thanks! I was not aware of the "Smart Keys" option so it's unlikely that I enabled it intentionally.

**Comment by devoncarew** [comment]
closing in favor of https://youtrack.jetbrains.com/issue/WEB-28954
