### ISSUE TITLE
Should open two files for plugin projects

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#1370]
The .idea/workspace.xml file is primed to open editors on two files when a plugin project is created. If the project is created from the command line, then opened in IntelliJ, the two files are opened in editors.

If the project is created from the `New` menu item in the IDE then only one file is opened.

@alexander-doroshko does this sound at all familiar to you?

**Comment by devoncarew** [comment]
Steve, I ran into some issues months ago that some similar. I believe theres a race condition on project creation and `flutter create`. If run from IntelliJ, I think it ends up using the metadata files that it creates in preference to the ones that `flutter create` does. So, when driven from IntelliJ, we don't get all (any?) of the settings that flutter create is trying to write; when run from the command line, and later opened in IntelliJ, we get all the settings. Does this sound like what you're seeing?

**Comment by alexander-doroshko** [comment]
Yes, **existing project opening** (which effectively happens if you create a project from command line) and **new project creation** from the IDE are 2 different branches of code that is executed. On new project creation IDE used to think that it **writes** the project metadata files, not **reads** them. AFAIK scenario, when new project wizard calls 3rd party tool to generate project metadata files, has not been implied and therefore tested before.

**Comment by stevemessick** [comment]
What Alex said :) When Android Studio (and probably any IDEA variant) creates a project it writes several files before starting the `flutter create` process. Flutter won't overwrite existing files, so the lines we add to workspace.xml that cause two files to be opened do not get written, since workspace.xml is one of the files created early.

There may be a way to initialize the project with two files open. I'll look into that. Someday. I don't think it is high priority.

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/1375
