### ISSUE TITLE
Android Studio doesn't "remember" Flutter SDK path for projects with no metadata

### ISSUE THREAD

**Issue by ksdboasit** [flutter/flutter-intellij#1497]
Summary:
Android Studio doesn't automatically set Flutter and Dart SDK paths, when opening a new project where the metadata has been deleted.

What steps will reproduce the problem?
1. Open a terminal
2. Create a new Flutter project ie. "flutter create foo_bar"
3. "cd foo_bar"
4. "rm -rf .idea"
5. "rm foo_bar.iml" 
6. Start Android Studio
7. Open the newly created project.

What is the expected output? What do you see instead?
Expected:
Android Studio "remembers" the SDK paths and creates the relevant metadata.

Actual:
Android Studio tells me that Flutter (and Dart) SDK are not configured.

What version of the product are you using?
Flutter
    • Framework revision 7298f9ca0b, 2017-11-10 08:09:14 +0100
    • Engine revision e92933611a
Android Studio v. 3.0
    • Flutter plugin version 19.0

On what operating system?
macOS Sierra 10.12.6

Please provide any additional information below.
Once an SDK path has been manually set for flutter, everything seems to be fine.

**Comment by alexander-doroshko** [comment]
Sounds like an expected behavior to me.
Project metadata (.idea folder and *.iml files) is exactly the place where the IDE stores information about the SDK and other project-specific settings.
Opening a project without metadata effectively means creating a new project based on some folder with some files. And the IDE is smart enough to detect that this is a Dart/Flutter project and to suggest you to enable Dart/Flutter support as soon as you open pubspec or any Dart file.

**Comment by devoncarew** [comment]
We may still be able to do something here in terms of parsing and inferring the sdk location from a `.packages` file, if one exists.

**Comment by ksdboasit** [comment]
You are right, that it is basically what one should expect, but this never happened with IntelliJ, which is why I decided to mention it.

**Comment by devoncarew** [comment]
@ksdboasit, thanks for the feedback (and sorry for the delay!). We did implement something like this: https://github.com/flutter/flutter-intellij/blob/e097480625885b14c6e818bde47d88bc99ad6b61/src/io/flutter/sdk/FlutterSdkUtil.java#L248
