### ISSUE TITLE
Make default position for the Flutter Inspector be docked on the bottom of the screen

### ISSUE THREAD

**Issue by jacob314** [flutter/flutter-intellij#1843]
There are a number of UI polish items that need to go along with moving the default position:

1. Duplicate the Toggle Select Widget Mode toolbar action into the debug and run views, as alternative ways to access the inspector view.
2. Move the property panel to the right side instead of bellow. Ideally we should just detect the ratio of width to height of the inspector window and change the property location accordingly.

**Comment by devoncarew** [comment]
Adding this to 'on deck' so that it's categorized.

I suspect that the view will be written such that its responsive, and will change its layout based on being vertical or horizontal.

But most users likely won't change where the view is docked from the default, so we should be pretty comfortable with our choice of the default docking spot. Some things to take into account - besides the best layout and size for what the inspector needs to display - is what other things the user will want to see at ~the same time, like the console output.

**Comment by devoncarew** [comment]
@jacob314 , I think we're not going to do this now?
