### ISSUE TITLE
Could not find a Flutter SDK - VS Code

### ISSUE THREAD

**Issue by tochanenko** [flutter/flutter-intellij#1860]
Error while creating a new project. IntelliJ IDEA also has an error: it endlessly shows progress line on creating new project.
I have installed Flutter via CMD using git command, then used `flutter`, `flutter doctor` and then `flutter upgrade`
the Path is listed correctly (C:\Windows\System32\flutter\bin)
On my second PC everything works well. Could it be cause of username? On laptop it uses cyrillic symbols

![flutter](https://user-images.githubusercontent.com/34678912/36833904-a0e83e98-1d39-11e8-8eb4-295987d02f33.jpg)

## Steps to Reproduce

Ctrl+Shift+P -> Flutter: New Project

## Version info
[√] Flutter (Channel beta, v0.1.5, on Microsoft Windows [Version 10.0.16299.248], locale ru-RU)
    • Flutter version 0.1.5 at C:\Windows\System32\flutter
    • Framework revision 3ea4d06340 (7 days ago), 2018-02-22 11:12:39 -0800
    • Engine revision ead227f118
    • Dart version 2.0.0-dev.28.0.flutter-0b4f01f759

[√] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at C:\Users\Владислав\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-23, build-tools 23.0.3
    • Java binary at: D:\Android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] Android Studio (version 3.0)
    • Android Studio at D:\Android\Studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.

VS Code:
Версия 1.20.1
Фиксация f88bbf9137d24d36d968ea6b2911786bfe103002
Дата 2018-02-13T15:33:21.935Z
Оболочка 1.7.9
Отрисовщик 58.0.3029.110
Узел 7.9.0
Архитектура ia32

**Comment by mit-mit** [comment]
For VS Code issues, can you please file in https://github.com/Dart-Code/Dart-Code/issues ?

**Comment by stevemessick** [comment]
@DanTup

**Comment by DanTup** [comment]
@tochanenko Have you rebooted since updating PATH? Windows seems to be bad for giving Code a stale path. You could try [v2.10 Beta 1](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.10.0-beta.1) which has some improvements (including letting you browse to the SDK if we don't detect it).

If neither of those help, please raise a case at the address above or grab me in [Gitter](https://gitter.im/dart-code/Dart-Code) and we can debug.

**Comment by tochanenko** [comment]
@DanTup I reinstalled Flutter into D:\Android\ from C:\Users\Владислав\ and now everything is fine

**Comment by DanTup** [comment]
@tochanenko I tried putting Flutter in a folder with that name and it seemed to work ok. My guess is that it was something else to do with the setup.

We can debug if you (or anyone else) can repro, but otherwise I don't think there's much we can do here (for Dart Code or IntelliJ) so gonna close this.
