### ISSUE TITLE
Generates relative instead of package path when importing files under project's lib/ directory

### ISSUE THREAD

**Issue by tamcy** [flutter/flutter-intellij#2015]
When using code completion to generate codes of missing file import, the plugin always generates a `package:` style import, even when importing from within our own package. But this can break things as ["main.dart" is imported relatively, not as a package](https://groups.google.com/d/msg/flutter-dev/4RSZlcp3x_E/n4k7xEgJCQAJ). It'd be better if relative path syntax is used.

**Comment by stevemessick** [comment]
@pq could you take a look and help decide who's best to follow up with this?

**Comment by pq** [comment]
I think the general rule is that if you use relative imports, all your imports should be relative, otherwise all should be absolute.  Problems arise when there's a mix.   In practice, I think @zoechi's advise is spot on.  FWIW, if you want the linter to keep you on the rails, you might consider enabling [`avoid_relative_lib_imports`](http://dart-lang.github.io/linter/lints/avoid_relative_lib_imports.html)...

cc @bwilkerson, in case he wants to chime in.

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#32690
