### ISSUE TITLE
Project Location is misleading in project creation dialog on Android Studio

### ISSUE THREAD

**Issue by Rissmon** [flutter/flutter-intellij#2035]
I am not able to create a new project when I point to a different directory.
 Getting error given below:

![changepackage](https://user-images.githubusercontent.com/28339332/38133520-3cae02e0-342d-11e8-8b5a-8f8702e08b9b.png)

The directory name was Flut . I was trying to create a new project inside the `E:\WorkSpace\Flut `folder.

![changedirectory](https://user-images.githubusercontent.com/28339332/38133581-76bbf24e-342d-11e8-96af-109fe0029b84.png)

**I am able to create a new project inside**  E:\WorkSpace, but when I change the directory I am getting the error.

## Version info
Waiting for another flutter command to release the startup lock...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.2.3, on Microsoft Windows [Version 6.3.9600], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] Connected devices (2 available)

• No issues found!

**Comment by stevemessick** [comment]
That UI isn't as intuitive as it should be. The project location needs to include the application name. Application names have to follow Dart package syntax rules (no caps, among other things). If you expand the error message you'll see more detail about that.

We should probably change the UI so that the project location specifies the parent directory where the project is created.

**Comment by Rissmon** [comment]
Yes, I am able to create a project when I named project location following Dart package syntax rules.
![parentfolder](https://user-images.githubusercontent.com/28339332/38147486-2c2de64a-3470-11e8-9ae5-240b13453891.png)
