### ISSUE TITLE
use flutter in different IDE in team

### ISSUE THREAD

**Issue by javadbat** [flutter/flutter-intellij#2067]
hi  we are a team and start using flutter app in different  IDE and our front-end team use VSCode and backend team use intellij .
when we run flutter doctor we get no problem and output is like this:
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.2.4-pre.40, on Microsoft Windows [Version 10.0.16299.309], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.0)
[√] Connected devices (1 available)

• No issues found!
and when we try flutter run in vscode we get following error :
     Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.51.
so we replace all android folder and it work but i dont think its a proper solution for our problem can you fix this problem .

**Comment by bwilkerson** [comment]
@devoncarew @DanTup

**Comment by devoncarew** [comment]
@javadbat, I suspect this is not a IntelliJ / VS Code issue. Likely you would have seen the issue from gradle if you had tried to `flutter run` your app from the command line.

I'm not sure what the underlying issue is myself, but you can try asking to see if people have hit similar issue on the gitter channel (gitter.im/flutter/flutter) or on stack overflow. If it looks like there's a problem, the flutter/flutter repo would be the right place to report this. Thanks!
