### ISSUE TITLE
Type Hierarchy issue

### ISSUE THREAD

**Issue by loveship00** [flutter/flutter-intellij#2296]
why can't view subtype of a specific class in dart sdk?

**Comment by jacob314** [comment]
This also impacts `package:flutter` as well as the dart sdk.
I suspect that currently we only show implementations in the user's local project instead of showing all implementations. Showing "no implementations found" for `class Widget` is very confusing.

Repro:
Use "Go to implementations" on the Widget class from within a project that imports package:flutter
versus use "Go to implementations" on the Widget class when package:flutter.
![image](https://user-images.githubusercontent.com/1226812/40808370-bc8c909c-64db-11e8-8d00-5b173640a515.png)

**Comment by scheglov** [comment]
WIP https://dart-review.googlesource.com/c/sdk/+/57760
