### ISSUE TITLE
consider using gradle for the project build?

### ISSUE THREAD

**Issue by quangson91** [flutter/flutter-intellij#2385]
We may consider using grade for this project.
IMO, 
+ it is more flexible
+ integrate with CI better
+ setup project for development is easier
+ Support kotlin in Travis CI. (Because I tried to write kotlin for this project, it worked well on my computer, but seems Travis can't pass - compile failed)

Link ref: https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html#add-gradle-support-to-an-existing-plugin

**Comment by devoncarew** [comment]
Thanks for the suggestion! We initially experimented with a gradle build for the plugin, but ran into issues with the fact that the Flutter plugin needs the Dart plugin installed in order to build.

At this point, we have a build system that works, and is easy to work on and adjust to changes in the build. So, I think we'll stay on the current build system, absent a strong incentive to move. I'll keep this idea open so we can comment on the future, as more information or requirements surface.

**Comment by quangson91** [comment]
@devoncarew yeap. That'd be great. 
I post this issue as a note for the future.
:)
Thank for considering.
