### ISSUE TITLE
Autocomplete ignores types

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter-intellij#2478]
`flutter create dummy`

Open `main.dart`.
Find `Colors.blue`, delete `blue` and get the autocomplete at that cursor position.
One of the options suggested is `Colors.accents`, which isn't valid at that point in the code.

**Comment by devoncarew** [comment]
`Colors.accents` wouldn't be, but there could be follow-on fields of `accents` that would be valid there. People also use completion for discovery, so I think we don't want to hide fields on a class. We can - and I believe do - use the type of a field to inform the weight of a code completion suggestion.

**Comment by devoncarew** [comment]
I believe this is working as intended -

**Comment by Hixie** [comment]
FWIW, this specific issue is leading to a number of difficulties for users. People start with the `flutter create` template, go to the line where we specify the primary swatch, and try to edit it using autocomplete to guide them about what's valid. So e.g. they try "Colors.white", which fails (but only at runtime), or "Colors.accents", which also fails (during analysis). In both cases they get confused.

cc @InMatrix

**Comment by InMatrix** [comment]
I just reproduced this issue. It was surprising to me Colors.white is not a MaterialColor while Colors.blue is. This seems to be inconsistent, and there is no visible cues to suggest these two properties are of different types. I wonder if this is an API design issue as much as a tooling issue. If we simply hide Colors.white when types don't match, the user might find it surprising that there is no white in Colors. 

As far as Colors.accents, I'm not too concern about it, since the name suggests it's not a color and IntelliJ doesn't show a color preview for it in the autocomplete dialog. However, I wouldn't argue against hiding/moving it down the list when types don't match, either.
