### ISSUE TITLE
Launch config cleanup

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#258]
Can we do anything to pre-populate the launch config names, after the user has chosen a launch script?

**Comment by pq** [comment]
Not sure what you mean by this one...  Could you elaborate?

Here's what I see.

<img width="299" alt="screen shot 2016-10-13 at 6 15 08 am" src="https://cloud.githubusercontent.com/assets/67586/19350392/6b5a8a3e-910c-11e6-9ec4-5c02cc7c8ac8.png">

**Comment by devoncarew** [comment]
This is when creating a new launch configuration - the user has to do a bunch of data entry, and I'm wondering how much we could automate.

**Comment by stevemessick** [comment]
Are you referring to this form?

<img width="835" alt="screen shot 2016-10-14 at 7 07 04 am" src="https://cloud.githubusercontent.com/assets/8518285/19390410/dcd7082e-91dc-11e6-9626-7c767de6943d.png">

I think that could use some clean-up. I believe the only required fields are the config name (`Unnamed` in this example) and the path to the file. And I'm not even sure the file is absolutely required, since it doesn't appear anywhere in the `app.start` command.

If we allow one project to contain several Flutter apps then we'd have to specify the CWD for the app in the launch config. Not sure if that is supported.

If you're thinking we should put something appropriate into the `Name` field then perhaps we could extract the app name from `flutter.yaml` and disambiguate with a numeric suffix.

The `app.start` command has `route` and `target` parameters that we are not using. Should fields be added to the form for them? (I admit to not knowing their purpose.)

Do you think Flutter devs will have several launch configs for each app? Might be worth checking with UX researchers.

**Comment by devoncarew** [comment]
I think they'll likely just have one launch config per app. You can have several apps per project - that's what the `target` field is for. It defaults to `lib/main.dart` - we should populate it with the info from the `Dart file:` field (but probably sending it in as relative to the project).

We probably don't need to expose the `route` arg - we can if there's demand. We may want to add a `support hot reload` option and default it to true.

`Program arguments:` I don't think we need -

**Comment by pq** [comment]
> Program arguments: I don't think we need -

@devoncarew, @stevemessick are we still in agreement that this good to remove?  What about working directory?

**Comment by stevemessick** [comment]
As implemented in the superclass (Dart) program arguments would be sent to the flutter command line (i.e. starting the daemon) so we don't want that. I don't recall an option to send arguments via the flutter tool to the app when it is launched so this argument wouldn't make sense even if reimplemented (unless I'm mis-remembering).
Sounds like working directory is not needed.
I also wonder if `Dart file` should be renamed to something more fluttery.

**Comment by pq** [comment]
Awesome.  Thanks Steve.

For reference, here's what [AS does](https://developer.android.com/studio/run/rundebugconfig.html#opening).

> I also wonder if Dart file should be renamed to something more fluttery.

👍 

I'm inclined to rename it as well.  `Flutter app`?

cc @sethladd

**Comment by sethladd** [comment]
> I'm inclined to rename it as well. Flutter app?

Great idea.

**Comment by devoncarew** [comment]
> What about working directory?

This is being used.

> Flutter app?

We do want it to be clear that they should be selecting a Dart file.

**Comment by pq** [comment]
> We do want it to be clear that they should be selecting a Dart file.

Good point.  We could do this with validation and feedback but helping them not make a mistake in the first place would be better.  Thoughts?

**Comment by sethladd** [comment]
Could we find all scripts that have `runApp` in them?

**Comment by devoncarew** [comment]
> Good point. We could do this with validation and feedback but helping them not make a mistake in the first place would be better. Thoughts?

I mean, we should just make it unambiguous with the text. `Flutter app` is what they'll end up running, but I wouldn't want them looking around their disk for a flutter app file. `Dart file` is clear as to what to select. So is something like `Dart entry-point`.

**Comment by pq** [comment]
> So is something like Dart entry-point.

I think we have a winner! 🎉
