### ISSUE TITLE
Document daemon protocol for updating breakpoints

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#273]
Document how to communicate new breakpoint locations when new sources are hot reloaded during a debugging session.

**Comment by mit-mit** [comment]
@johnmccutchan is this you?

**Comment by devoncarew** [comment]
Here's the current docs of the `app.restart` command: https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode#restart (`{ String appId, bool fullRestart }`)

Adding breakpoints is defined here: https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#addbreakpoint (in the service protocol doc).

```
Breakpoint addBreakpoint(string isolateId,
                         string scriptId,
                         int line,
                         int column [optional])
```

And we call `_reloadSources` from here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/vmservice.dart#L757

Given all that, I think we should document `_reloadSources` in the service protocol, consider renaming it to `reloadSources`, adding a param to it (a list of maps: `isolateId, scriptId, line, [column]`), and have it return a structured type that includes a result status message, and a list of `Breakpoint`s. The daemon `app.restart` command can then be augmented to pass in a list of breakpoint info, and return the status message and list of breakpoint results. Thoughts?

**Comment by johnmccutchan** [comment]
@devoncarew Expanding `reloadSources` with side data won't scale because a debug client may want to do a variety of operations before resuming execution of the isolate. I have a [CL](https://codereview.chromium.org/2411153002/) that will land shortly that will add an optional `pause` parameter to `reloadSources`. When set to `true`, the isolate will pause in the debug loop. While the isolate is paused, debug clients can issue any service requests including `addBreakpoint`. Once a client has updated the state, it can resume the isolate.

I would expect this structure would allow you to reuse the code that runs at isolate startup for registering breakpoints.

Similarly, the daemon's `app.restart` should probably be expanded to support requesting the application be 'paused' after the restart so that more operations can be performed before execution resumes.

**Comment by devoncarew** [comment]
Makes sense, and

> I would expect this structure would allow you to reuse the code that runs at isolate startup for registering breakpoints.

yup, this will be easier for clients to implement.

**Comment by johnmccutchan** [comment]
Is there anything left here? When a client requests a reload they can pass in the `pause` parameter and then once the reload is completed, restores all breakpoints in reloaded scripts.

**Comment by devoncarew** [comment]
Yup, this is done. The wiki doc has been updated w/ the new `pause` param (https://github.com/flutter/flutter/wiki/The-flutter-daemon-mode#restart).

It would be great to update the service protocol doc with the new pause event.
