### ISSUE TITLE
flutter and dart sdk path settings should not be presented in the app settings dialog (since they can be different for different projects)

### ISSUE THREAD

**Issue by Soundbytes** [flutter/flutter-intellij#2810]
I find it very misleading that these per project settings are made available through the program settings/app preferences dialog. Could the settings please be moved to a more appropriate place?
It took me quite a while to finally understand that these are in fact meant to be per project settings and not global as indicated by their position in the menu structure.

Steps to repeat:
(1) open/create a flutter project
(2) change flutter/dart settings in preferences > Languages and Frameworks > ...
(3) open/create another project
(4) Look up the dart/flutter settings. 
(5) The recently made changes are not present here.

Why is that an issue:
https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/preferences/

Thanks!

**Comment by jwren** [comment]
Assigning to @pq as he has worked on the getting started experience more than myself.

I suspect unfortunately that the notions and architecture offered by IntelliJ simply do not map to your notion of "session to session".  I'd also guess here that if we had the Flutter SDK path be automatically set project to project it might cause confusion for some users.

**Comment by Soundbytes** [comment]
Sorry for the confusion. I have now updated the header since that lead you to miss my point.
I would never expect the setting to be per session. Of course it is persistent and valid for the current project.
I also do appreciate that it is not an app wide setting that would have to change any other projects. 
What bothers me is that IMO it does not belong in the app settings dialog because that leads users to expect otherwise. (and rightfully so)
All I ask is that you please do not present any **Project** settings within the **Application** settings dialog. That will surely ruin the user experience. (At least for me it does)
For the apple platform there is even an explicit design guideline against that. (See link in my previous post)  On the windows side I am afraid there are no such rules that I am aware of. Still there are best practices and customs that one should try to adhere to.  

And of course intellij has an dedicated dialog for the project specific sdk settings. 
For the Mac and windows versions it can be found under: 
**File > Project Structure > Platform Settings > SDKs**
(with Linux it should be the same)

Thanks!

**Comment by alexander-doroshko** [comment]
The current solution is made on IntelliJ Platform end and inherited by all IntelliJ Platform-based IDEs, including IntelliJ IDEA, WebStorm and Android Studio. Indeed, some pages in Preferences (Settings on Windows/Linux) are IDE-level (global), others are project-level. The latter are marked with a `For current project` icon:
![image](https://user-images.githubusercontent.com/4499789/48490268-1a2f8500-e836-11e8-9050-24312c636ae6.png)

Some users find this solution not ideal. What I can say for sure is that the approach shouldn't and can't be changed by plugin developers. This could only be done by IntelliJ Platform developers and UI/UX experts at JetBrains. There are some internal discussions at JetBrains on the topic. Unfortunately, the problem (if any - not everybody agrees it's a problem) is not obvious and not easy to fix to satisfy all kinds of IDE users. Suggestions are welcome on [JetBrains issue tracker](https://youtrack.jetbrains.com/issues/IDEA) . Note that changes in this area affect several millions of JetBrains IDE users, that's why devs may be not so quick with adopting new approaches.
