### ISSUE TITLE
<Tooling request> . Android Studio support for Add2App

### ISSUE THREAD

**Issue by zoechi** [flutter/flutter-intellij#2924]
@neiljaywarner commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/25043)

I know this might be far off, but perhaps we could have an issue to track it or a card in Add2app project board - can we have Android Studio google support for Add2app.  file->Add Flutter or similar?

That would be really nice both in terms of 
a) automating the work
b) making sure it worked right
c) A general feeling of this being a well-supported mature procedure that existing large apps can feel more comfortable trying.

Huge Bonus points if it is bundled with Android Studio by default some day, even if a long time from now - giving the feeling that Flutter is a "first class citizen" for Android apps, as Kotlin support came after several years.

**Comment by stevemessick** [comment]
With your Android app open in Android Studio, use `File > New > New Module` to open the module picker.

<img width="887" alt="screen shot 2018-12-06 at 10 33 45 am" src="https://user-images.githubusercontent.com/8518285/49605119-876d9c00-f944-11e8-911c-3dc7a2008d23.png">

Select "Import Flutter Module" and work through the rest of the wizard. The Flutter project must have been created as a Module (`flutter create --template module`, or using the Module type from Android Studio's new project wizard). Edit your Android code as instructed in the add2app doc,
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#use-the-flutter-module-from-your-java-code

You may need to re-sync the files with Gradle in the Android project, if `Flutter` can't be resolved. That's easy with `File > Sync Project with Gradle Files`, but really should be done automatically. Launch it and switch to the Flutter module project (you can have both projects open in separate windows, recommended). Click the `Flutter Attach` button on the toolbar if you want to debug it. Just make sure to attach before activating the Flutter code.

For this demo I just created a simple Android app with a Basic Activity then edited the code to replace the onClickListener. After launching I clicked the Mail icon.

<img width="312" alt="screen shot 2018-12-06 at 10 47 48 am" src="https://user-images.githubusercontent.com/8518285/49605375-28f4ed80-f945-11e8-9ec3-81ed0e58bc36.png">

**Comment by neiljaywarner** [comment]
@zoechi  please consider if this ticket needs re-opened or another ticket - if some of those items can be addressed, ideally by getting the automatic import to not fail as a nice start if possible at some point.

**Comment by stevemessick** [comment]
@neiljaywarner I am glad you got it working! Is there any chance you could share the two files you had to edit? (settings.gradle & app/build.gradle) The auto-editing code could be made more robust if we had more examples to test with.

Flutter modules do not support kotlin yet. Not the last time I checked, anyway.

`my_flutter` is the name of the module created by flutter. I don't think it needs to be explained again since it was just created at the beginning of the section on Android. But feel free to express a different opinion to the flutter tool folks :)

I think the colons you are referring to serve the same function as ellipses. At least, I read it that way. Again, good feedback for the folks implementing and documenting add2app.

Nice to see someone is having some success with this; modules have not been out as long as the rest of the project types.

**Comment by stevemessick** [comment]
Ah, I get it now, and I agree that code samples in Kotlin would be nice to have. I was thinking under-the-hood that Flutter modules don't generate any Kotlin, but that isn't relevant to your question.

Thanks for the project generation details. I guess that's my fault for not generating a Kotlin-based Android app to work with. I need to keep up :)
