### ISSUE TITLE
consider checking for flutter framework updates

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2932]
We should consider checking for flutter framework updates as part of the IntelliJ 'check for updates' action.

**Comment by pq** [comment]
FWIW I did some poking around (and confirmed w/ Alex) and there doesn't seem to be a way to easily hook into the update check.  The best angle is probably to do our own update check the way we do in the Dart Plugin.

Popping up, I do think this would be very handy since so many of our exchanges with folks begin with "could you update you SDK and try again?"  I'll look a little deeper.

@devoncarew feel free to re-assign if you're already tackling. 👍

**Comment by devoncarew** [comment]
Cool, thanks for looking into it. I think android studio has custom behavior here, but they may replace the action completely (which isn't something we're likely to want to do).

**Comment by jwren** [comment]
With recent changes and going forward, the Flutter IJ plugin will be required to work with recent SDK versions, see recent changelog for details.
