### ISSUE TITLE
Support for other Intellj based IDEs ?

### ISSUE THREAD

**Issue by Gee5ive** [flutter/flutter-intellij#3159]
Not really an issue with the plugin per se, just wondering why there's no support for other IDEs based on the IntelliJ platform? I use Go and goland primarily and it would be cool to be able to create flutter apps from within the same IDE, is there some technical details preventing this? The dart plugin is already available, so I am not exactly sure why there would be?

**Comment by kenzieschmoll** [comment]
@devoncarew can you add any insight here? Thanks.

**Comment by devoncarew** [comment]
We currently support IntelliJ (CE and Ultimate) and Android Studio. Each variant has some small support costs - small platform differences - like for WebStorm - or version skew for the platform APIs. We limit the number of supported products in order to reduce support costs here - we think with the two above platforms we've captured the bulk of the ones that users would be coming from.
