### ISSUE TITLE
Android Studio show error message when we add mipmap image in src.

### ISSUE THREAD

**Issue by gaurav-bodhare** [flutter/flutter-intellij#3160]
It works properly but showing error message.

**Comment by kenzieschmoll** [comment]
@stevemessick thoughts?

**Comment by gaurav-bodhare** [comment]
I have generated a simple app using flutter in android studio. I was adding splash screen to it. I un-commented 
`<item>

    <bitmap
        android:gravity="center"
        android:src="@mipmap/image_name" />

</item>`

in launch_background.xml file of android resource and added image 'image_name'.
In IDE it shows image_name in red also shows that there is error but it works properly.
Showing error is bothering me because I got confused initially.

**Comment by gaurav-bodhare** [comment]
@kenzieschmoll  Anything else you want me share here??

**Comment by kenzieschmoll** [comment]
I think we have enough info - adding this to our backlog. Thanks.

**Comment by stevemessick** [comment]
The recommended way to edit the Android module is to open it as a separate project in Android Studio. See the menu Tools > Flutter > Open for Editing in Android Studio.

It is not perfect, but it is consistent with iOS support. The ideal solution for Android would support all the operations provided by full Gradle analysis (which happens when opening the module separately) and take no additional time (but Gradle analysis is very time-consuming).
