### ISSUE TITLE
[Feature request] Open android module in Intellij

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter-intellij#3208]
Thanks for this awesome plugin
I have a small feature request
"Open for Editing in Android Studio" doesn't really makes sense
Intellij IDEA has Android plugin, so what's the point of launching separate IDE?
Can't plugin just open android module in separate window of Intellij?
Same problem with "Open for Editing in XCode", when you have AppCode installed

**Comment by stevemessick** [comment]
We wouldn't consider either of those requests to be "small". The engineering effort is rather large, anyway. We've actually made some progress toward eliminating the need to open a new project to edit Android code. In the Flutter plugin preferences there is an experimental option to enable indexing of Java/Kotlin. Unfortunately, it is broken in version 33.0 of the plugin but will be fixed in 33.1, coming out in a couple days. Integration with AppCode is a much harder problem. You'd have to take that up with Jetbrains, since it isn't an open source project.
