### ISSUE TITLE
Improve Lambda autocomplete 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#3254]
having something like:

```
myStream.stream.listen()
```

won't autocomplete into a lambda, which does work for Java and is very handy.

**Comment by alexander-doroshko** [comment]
@feinstein I'm not the right person.
Code completion is powered by the Dart Analysis Server from the Dart SDK. So usually code completion issues are tracked in https://github.com/dart-lang/sdk/issues/, label: `area-analyzer`. No actions needed, I think Flutter plugin developers will move the issue there if they want to.

BTW I think the issue description could be improved so that developers understand what you do, what you expect and what you get instead.

**Comment by pq** [comment]
Thanks for the triage @alexander-doroshko!

@feinstein: I'll move this one over.  Cheers for the report!

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#36112

**Comment by feinstein** [comment]
Oh, I see, thank you anyway @alexander-doroshko
