### ISSUE TITLE
Open for Editing in Android Studio uses incorrect AS installation

### ISSUE THREAD

**Issue by nick-morhun** [flutter/flutter-intellij#3274]
## Steps to Reproduce

A. Navigate to any Android source file. Click a suggestion at the top "Open for Editing in Android Studio".

B. Go to Tools -> Flutter -> Open for Editing in Android Studio

Result: IDE Error: "Exception: Cannot run program "E:\android-studio-beta": CreateProcess error=5, Access is denied" (it is my Beta AS 3.4 path which is detected in an undocumented way by Flutter)

Expected: If multiple AS versions are installed, allow a user to select which to use; or use currently running AS version.

## Version info

[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale uk-UA)
    • Flutter version 1.2.1 at E:\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:/AndroidSDK
    • Java binary at: E:\android-studio-beta\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] Android Studio (version 3.4)
    • Android Studio at E:\android-studio-beta
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code, 64-bit edition (version 1.26.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

**Comment by nick-morhun** [comment]
Yes, it works when Flutter project is the only one opened.

**Comment by stevemessick** [comment]
Thanks! It sounds like there is a timing issue during initialization when windows are being opened. It is supposed to detect Android Studio vs IntelliJ and install the correct action handler but it isn't doing the right thing.

**Comment by Ale-Digitale** [comment]
I confirm this [ very annoying ] bug.

This happens even if you have just ONLY ANDROID STUDIO installation.

If you click on "Open for editing in Android Studio" at the top of the INTELLIJ IDEA IDE, you get an exception ( see attached screenshot ) and INTELLIJ FAILS TO LAUNCH ANDROID STUDIO.

There is a workaround:

From the command prompt, if you change the FLUTTER config with:

"flutter config --android-studio-dir PATH-TO-THE-ANDROID-STUDIO-EXECUTABLE-INSTEAD-OF-DIR"

making it pointing to the ANDROID STUDIO'S EXECUTABLE instead of the path dir, IT WILL FINALLY WORKS... and INTELLIJ launches ANDROID STUDIO correctly.

But this can't be the right way of doing things... because this workaround "breaks" the flutter config.... causing FLUTTER DOCTOR to fail.

I already submitted this to JETBRAIN's bug tracking system and they said that this must be a Flutter's plugin error: https://youtrack.jetbrains.com/issue/IDEA-216200

There must be sort of a bug somewhere... please investigate it.

![error](https://user-images.githubusercontent.com/39025003/59544109-bb3b0700-8f0f-11e9-893c-fb972c451941.png)
