### ISSUE TITLE
Tooltip blocking my ability to cmd-click on symbol

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter-intellij#3346]
Using Flutter plugin `34.0.1` in Android Studio `3.3.2` running on OS-X `10.13.6`

If I try to hover over a symbol and cmd-click into it to see its definition, a tooltip jumps in the way, keeping me from clicking into the definition.  See attached movie:

![no-cmd-click](https://user-images.githubusercontent.com/15253456/55451262-0d15f700-5587-11e9-8a88-3af42364a580.gif)

**Comment by stevemessick** [comment]
This is a long-standing issue in IntelliJ. I don't think there is anything we can do about it. Here's the link to the Jetbrains issue:
https://youtrack.jetbrains.com/issue/IDEA-55097

It is 9 years old. You could up-vote it. Toward the end is a description of how to disable tooltips, if that helps.

@jwren Didn't we once have a discussion with Jetbrains about moving the location of the tooltip above the line with the cursor, rather than below it? Or was that in Eclipse?

**Comment by jwren** [comment]
This is simply part of the territory with AS and IntelliJ in general.  I'd suggest disabling the tooltips and learn the action/keystrokes: Ctrl+Q (Linux) or F1 (Mac).

**Comment by stevemessick** [comment]
Gee, I wish I had a consistent F1 key :(
Anyway, thanks for the input. I'm closing this now.
