### ISSUE TITLE
device pulldown not populated when there's no network connection

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#3496]
When I was without a network connection, I noticed that the device pulldown didn't populate. I tracked this down to:

- the `flutter daemon` process was blocked on startup due to another flutter process having the startup lock (`Waiting for another flutter command to release the startup lock...`)
- this process was the one listing flutter samples (`flutter create --list-samples`)
- there were 15 sample listing processes running
- when run off-line, these process try an exponential, non-terminating attempts to connect to and download the catalog of samples
- there's a race condition in FlutterSamplesManager that will cause new requests to fire off if the initial one hasn't completed yet; it looks like FlutterSamplesManager.getSamples() is called several times a second and will fire off many (dozens?) of flutter create --list-samples

```
Download failed -- attempting retry 1 in 1 second...
Download failed -- attempting retry 2 in 2 seconds...
Download failed -- attempting retry 3 in 4 seconds...
Download failed -- attempting retry 4 in 8 seconds...
Download failed -- attempting retry 5 in 16 seconds...
Download failed -- attempting retry 6 in 32 seconds...
```

Concretely for flutter_tools:
- `flutter create --list-samples` needs to release the startup lock
- `flutter create --list-samples` should not re-try the download indefinitely

Instead of a command to download the samples index, we may want to change to a mechanism where the index if built on the flutter chromium bots, and included as part of the SDK. This would mirror how other sdk artifacts are provisioned.

@DanTup @pq

**Comment by DanTup** [comment]
Yikes!

I didn't realise it would keep retrying (or consider the lock). In VS Code we only run it when you explicitly run the command, so it's probably not hit all that much.

> we may want to change to a mechanism where the index if built on the flutter chromium bots, and included as part of the SDK

I think both @pq and I would much prefer something like that, but when we previously discussed it there were generally two issues:

1. We don't have a good way of including things in the SDK that come from building it (eg. if a git commit kicks off the build, we can't have it commit the samples back to the repo). Probably it'd need to be downloaded based on the hash or something (like other artifacts)

2. The original design of downloading samples was deliberate to allow users to get new templates even if they're not on the same SDK version (though I'm not sure this idea is all that useful since the docs only update with stable releases, and we probably don't need to optimise for people on non-current stable releases).

Moving the download from the editors to Flutter was a short-term fix to reduce them being out-of-sync (the `flutter create` command switches hostname for downloading the samples based on your Flutter branch, and we didn't want to leak that logic into the editors). I definitely think we need a plan for improving this though.

**Comment by devoncarew** [comment]
I think having this being just another sdk artifact makes sense. That way the samples are in-sync with the sdk you'd use to create them.

**Comment by pq** [comment]
> I think having this being just another sdk artifact makes sense. 

+1.  As @DanTup said, we discussed it and the current approach won out for the reasons described but I think at this point there are enough issues (and complexity) with it that we should seriously reconsider.

@DanTup: 

> Probably it'd need to be downloaded based on the hash or something (like other artifacts)

This sounds reasonable to me.

**Comment by devoncarew** [comment]
The issue with the device pulldown not being populated has likely been addressed by the flutter_tools commit. We should still re-visit the implementation of `FlutterSamplesManager` to ensure that it doesn't kick off more than one simultaneous flutter list samples process, and if a process takes a while to run, it should kill the process instead of letting it run indefinitely.

If we want to continue to support this sample creation flow, we should update the sdk to include the samples index. There are many other examples of doing this - it's s general flow for items that aren't committed to the github repo, but that you do want to be part of the sdk.

**Comment by pq** [comment]
> We should still re-visit the implementation of FlutterSamplesManager to ensure that it doesn't kick off more than one simultaneous flutter list samples process

Given the other issues we've seen with this approach (timing in general and the odd case where we can't write to `tmp/`), I'm inclined to go back to a simpler approach and run from our own cached index files until we fix this for real by having the index an artifact in the SDK.  I'm guessing if we had one for each of the last major versions people would not generally be bitten by skew. 

> If we want to continue to support this sample creation flow, we should update the sdk to include the samples index.

I think this is really the best option.  @DanTup: WDYT?

**Comment by DanTup** [comment]
> I'm guessing if we had one for each of the last major versions people would not generally be bitten by skew.

Right now, the SDK version isn't what's important. The issue is when the index we use and the website are out of sync. If our index has different samples in it compared to what's on the live docs (or `master` docs) then the user might pick a sample (from the index) and then get an error during creation (because `flutter create` tried to get that sample from the live site).

We moved away from the local indexes after there were "breaking changes" to those sample IDs (numeric suffixes) with resulted in errors. If we go back to shipping indexes, we need to be reasonably sure the sample IDs on the websites won't change unexpectedly again (probably they won't, the previous issue seems like a one-off).

> > If we want to continue to support this sample creation flow, we should update the sdk to include the samples index.
> 
> I think this is really the best option. @DanTup: WDYT?

Yep, this makes sense to me as a better fix. I'm not sure what the work is to do this though - I think all the current artifacts are built and uploaded as part of an internal build (and possibly all in the engine, not the Flutter repo?).

**Comment by devoncarew** [comment]
@pq, moving this into M36. There are ~2 issues in the IntelliJ code we should address, even taking into account the fix in flutter_tools:

- FlutterSamplesManager can fire start many copies of `flutter create --list-samples` in parallel
- FlutterSamplesManager lets the process run indefinitely (it should have a hard limit of something like 30 seconds, to account for the older flutter_tools)
