### ISSUE TITLE
show progress on project creation

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#3543]
As noted by @devoncarew in https://github.com/flutter/flutter-intellij/issues/3540:

> we don't show progress when creating a new flutter project, after clicking on the Finish button at the end of the Android Studio new project wizard flow. The UI pauses for ~10s, then a new project window is shown.

**Comment by stevemessick** [comment]
This is what we do:
<img width="558" alt="Screen Shot 2019-05-30 at 1 54 52 PM" src="https://user-images.githubusercontent.com/8518285/58664704-105a0480-82e4-11e9-8f37-a97e2d273b3f.png">

That's been the case since (almost) the origin of the Android Studio plugin. If you're not seeing that then we are going to need more detailed repro steps.

**Comment by devoncarew** [comment]
I didn't see any progress dialog; this was for AS 3.5. I'll double check, and see if it's consistent or intermittent.

**Comment by devoncarew** [comment]
This might be occurring on just my machine. I'd checked the "don't show again" to the dialog asking whether to create a project in the existing window or a new one. Perhaps that short-circuts something, and the progress dialog isn't show, or appears at a lower z-axis.
