### ISSUE TITLE
Make sure Android Studio can edit/debug both Android and Flutter modules

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#3553]
In an add-to-app scenario with an outer 'standard' Android app and an inner Flutter module, it would be nice to be able to bring both into the IntelliJ project and edit / debug both Android and Flutter code.

**Comment by stevemessick** [comment]
By "outer" and "inner" do you mean directories?

I created a sample Android project to experiment with. I added (via cmd-line) a Flutter module. The directory structure is (simplified):
- MyApplication
  - app
  - sample

The "MyApplication" and "app" directories were created by Android Studio, using a simple app template. The "sample" directory was created from the command line via:
 `flutter create --template=module --org=com.example.sample sample`

After adding and editing various configuration files I was able to get Flutter support in the same project window as the Android app.

<img width="1401" alt="Screen Shot 2019-06-12 at 8 40 42 AM" src="https://user-images.githubusercontent.com/8518285/59365807-0b3a8380-8cee-11e9-9658-a5ef53fd217c.png">

You can see in that screen shot that hot reload worked when the Flutter module was launched as a stand-alone app, and that Java syntax highlighting is present. Code completion works for both Flutter and Java files in the Flutter module. Since the root project is an Android app all the Android Studio support is available for it, too.

It is going to require a bit of work in the Flutter module template (in flutter_tools) to get this working out of the box. I had to add a Gradle build script to the Flutter project. I needed to change the sample.iml file to look more like an Android module rather than a Java module. And I had to edit `.idea/modules.xml` to add the Flutter module to the Android project. There may be more work required to get everything working; I just wanted to see if the basic approach was valid.

As for actual work that could be done in the IDE, we can add a new type of module to the New Module Wizard in Android Studio. We already have the ability to import an existing Flutter module, but we could add another option to create a new Flutter module and link it in to the Android project.

@xster Is this what you had in mind?

**Comment by xster** [comment]
Right, in this case the "outer" project is the "MyApplication" Android project and the "inner" project is the "sample" Flutter project. 

I think the desired functionalities would be 

- Editing both Java/Kotlin code in MyApplication/app and Dart code in sample/lib. Sounds like that already works
- Be able to run the Flutter sample project as an app and get hot reload / debug. Sounds like that already works too.
- Be able to pick the right Android flavor for the Android project but also toggle which Flutter mode I want to run debug/profile/release.
- Be able to run the MyApplication Android project and get Android debugging but also auto start https://github.com/flutter/flutter/issues/32824 and get Flutter debugging / hot reload when the user starts the Dart VM (which might not be at launch). 
- If I created MyApplication already (maybe git cloned), either link it to an existing Flutter module project or create a Flutter module project that will then link to this MyApplication. And in the IDE, the project types are correctly annotated.

**Comment by xster** [comment]
The work remaining here is documentation.

**Comment by stevemessick** [comment]
The documentation has been updated at
https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps
