### ISSUE TITLE
Unable to hot reload in android studio (Button is disabled)

### ISSUE THREAD

**Issue by eladkatz** [flutter/flutter-intellij#3578]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

opened a new project, wrote some code, ran it once on an android emulator.

made a change, hit save all expecting to see the hot reload button turn on, but it did not.

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

L:\Dev\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at L:\Dev\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at L:/Dev/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = L:/Dev/Android/SDK
    • ANDROID_SDK_ROOT = C:\Users\Elad\.android
    • Java binary at: L:\Dev\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at L:\Dev\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by jacob314** [comment]
Some notes:
1. Saving a file will trigger a hot reload by default. No need to click hot reload as well.
2. Can you reproduce the issue? Likely something went wrong and although your flutter app was running it was disconnected from your machine. For example, if you see a run/debug window in IntelliJ that means your app was connected otherwise your app likely became disconnected. In the console window you should be able to see why it got disconnected.

**Comment by eladkatz** [comment]
Thanks Jacob,
This was resolved by going back to sdk tools v28 and using a non-q emulator

**Comment by stevemessick** [comment]
Possibly related to https://github.com/flutter/flutter-intellij/issues/3235

**Comment by stevemessick** [comment]
Thanks for mentioning Android Q! It turns out we have a problem with Q. I filed https://github.com/flutter/flutter-intellij/issues/3652 for it.

In my case, the app was running on the emulator, but was disconnected from the IDE. That's probably why hot reload wasn't working -- the IDE couldn't talk to to the Flutter app.
