### ISSUE TITLE
Flutter doctor not running .It Is totally stuck. i have started upgrade but it is not fully completed due to problem..Again when i run flutter doctor it stuck .No command is running

### ISSUE THREAD

**Issue by Mallika-Tung** [flutter/flutter-intellij#3589]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jacob314** [comment]
We need more details to debug this issue. Are you able to reproduce the problem? How are you installing flutter? What does `flutter doctor -v` show if you are now able to run it successfully?
If you are able to reproduce the issue on the command line then you should file the issue here:
https://github.com/flutter/flutter/issues/new/choose

Thanks,
Jacob

**Comment by SmartInteractiveGroup** [comment]
Hello I have the same issue. Trying to solve it by adding in path link to the flutter directory. But no command is running. Flutter doctr -v, flutter help. They all stuck. just the cursos blinks all the time.
