### ISSUE TITLE
flutter upgrade to use "--force" command 

### ISSUE THREAD

**Issue by prudhviraj9999** [flutter/flutter-intellij#3657]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_
I am trying to upgrade flutter but it is showing error that local file issue 
i want to remove every change in flutter SDK directory but unable to use  "--force " command

## Version info 1.5.4.hotflix-2

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by pq** [comment]
Could you paste the entire error message?

Thanks!

**Comment by prudhviraj9999** [comment]
[flutter] flutter upgrade
Your flutter checkout has local changes that would be erased by upgrading. If you want to keep these changes, it is recommended that you stash them via "git stash" or else commit the changes to a local branch. If it is okay to remove local changes, then re-run this command with --force.
exit code 1


Thanks For responding @pq

**Comment by 1048300461** [comment]
I have same problem. How to solve it!!!!

**Comment by prudhviraj9999** [comment]
In Terminal , use command 

> source .bash_profile 

and then run , 

> flutter upgrade --force 

To remove changes in flutter directory, It will upgrade to recent flutter version

**Comment by 1048300461** [comment]
it can't work for me.

**Comment by AadeshGujjar** [comment]
So I encountered the same problem. This probably occurred because I have my flutter SDK installed in the E:\ directory rather than default C:\ directory.
This is how I solved it, 
1: Check where your Flutter Sdk is present. You can do this by creating a "New project->Flutter->Flutter Sdk" (This works if you have the flutter Sdk installed and configured, If you don't have it installed you can click on install Sdk option in the same "new Project->Flutter" window).
2:  Then open Terminal by going to bottom right corner of you IDE and then clicking on terminal.
3: Change your directory to the flutter sdk's bin location by Typing "cd _yourSdkLocation\bin". Here replace "_yourSdkLocation" with the directory address where your flutter Sdk is present.
4: Then run "flutter upgrade --force" 

Hope this Helps. :)

**Comment by thelastknightahk** [comment]
> In Terminal , use command
> 
> > source .bash_profile
> 
> and then run ,
> 
> > flutter upgrade --force
> 
> To remove changes in flutter directory, It will upgrade to recent flutter version

Thank sir. You solved really.

**Comment by jahid-ci-cd** [comment]
> In Terminal , use command
> 
> > source .bash_profile
> 
> and then run ,
> 
> > flutter upgrade --force


Thanks. It worked.

**Comment by haseeb0118** [comment]
I am facing the same run this cmd on your terminal it will b helpful for you. 
cmd : flutter upgrade --force

**Comment by adenehemia09** [comment]
run in terminal

`git stash`
and
`flutter upgrade --force`

The problem is hard to discuss here [https://stackoverflow.com/a/73700234/15876526](url)
