### ISSUE TITLE
Bring back "Remove widget" refactor

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#3898]
It seems that the "Remove widget" refactor was renamed to "Replace widget with its children" at some point. The new name doesn't seem to register in users' mind, as I have seen several users asking where the refactor went:
* https://twitter.com/meAndAlfred/status/1161044962856882183
* https://www.reddit.com/r/FlutterDev/comments/d7jahb/is_there_a_shortcut_to_remove_a_whole_widget_from/

Can we consider bringing the old name back?

**Comment by DanTup** [comment]
I think the name change may have come about due to confusion with the old name (I think it came up in the Dart-Code issue tracker). There's also a comment on the reddit thread linked above:

> When I hear remove widget it sounds like it should remove the whole subtree at given widget. Then replace should well replace the widget with its children.

There are some additional comments here:

https://www.reddit.com/r/FlutterDev/comments/d4l8qt/action_of_remove_widget_is_gone_in_vs_code/

including:

> 'Remove child' heavily implied that the whole widget would get removed (including it's child/children) but it only replaced the parent with it's child/children, so it made sense to change the name.

and

> Edit: My reasoning is actually wrong here, since all the descendants are also part of that widget. My bad.

My interpretation is that maybe neither name is clear. I think if you're looking to remove a widget (but leave it's children) looking for a "remove widget" refactor in isolation makes sense. However when you're not in that situation, being presented with "Remove widget" is a big ambigious.

Maybe we could have a name that contains "Remove widget" but is less vague (for example something along the line of "Remove widget (keep child widgets)" might suit both needs, though could probably be worded better). Having an action to remove the whole sub-tree ("Remove children (including children)") might also remove ambiguity?

**Comment by escamoteur** [comment]
What about 'remove this widget?

**Comment by devoncarew** [comment]
Sounds like something like renaming to:

- `Remove widget (keep child widgets)`
- or, `Remote this widget`

would increase clarity and discoverability.

Perhaps, we could add another refactoring option to help draw a distinction between what it does and around what the `Replace widget with its children` refactoring does?

- `Remove this widget` and `Remove widget and children`

**Comment by InMatrix** [comment]
> Remove this widget and Remove widget and children

This sounds reasonable, though I'm not sure how often the latter will be used. Maybe exposing `Extract widget and children` is more useful than `Remove widget and children`?
