### ISSUE TITLE
we don't pass in the flag (`--no-track-widget-creation`) to disable widget creation tracking

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4130]
Based on user settings, we do pass in the positive flag (`--track-widget-creation`), but not the negative one (`--no-track-widget-creation`).

Once we fix this, we should also verify that the `--no-track-widget-creation` (as passed into flutter run --machine) _does_ disable widget creation location tracking.

cc @jacob314

**Comment by devoncarew** [comment]
Let's remove the option altogether; users can always pass in `--no-track-widget-creation` in the additional args field of a launch configuration.

**Comment by jacob314** [comment]
There is one gotcha. Users with old Flutter SDKs will be negatively impacted if we remove it as they will suddenly stop running with --track-widget-creation.
Maybe we should specify the oldest flutter SDK we support with each Flutter IntelliJ plugin and warn users when their Flutter SDK doesn't match the expected version?
As a strawman, we could fix this option to add --no-track-widget-creation now and then remove it completely mid 2020.

**Comment by devoncarew** [comment]
Do you know what stable version of the Flutter SDK this was enabled in? I assume that the `--no-track-widget-creation` version of the flag has been legal (that we hadn't been using the args packages option to disable negation of the cli flag).

**Comment by DanTup** [comment]
I think this has been negatable since it was added in https://github.com/flutter/flutter/commit/2c05ecab9fb5d6e87b7cc028a38eb634757c5cf8#diff-09c5be1877aa83342be68006ff74cb82R117 (at least for `run` - some other commands it's not, but probably not relevant here). That changeset was apparently in v0.1.1 so I think it's relatively safe to always send.

It was only recently made default in Flutter (https://github.com/flutter/flutter/pull/43471), so it only really needs opting out for >= v1.10.15. I don't have easy access to the Flutter version in the debug adapter so I think I'll just always send it rather than wiring that up (I think v0.1.1 of Flutter is likely already unsupported in VS Code because of other assumptions over the past 18 months).
