### ISSUE TITLE
Paste sometimes pastes to the left of the caret

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#417]
Please see video below. I copy some text and then paste it. The paste appears to the left of the caret.

If I type the text instead, the editor behaves correctly.

![left-insert on paste behaviour](https://cloud.githubusercontent.com/assets/2978182/19977318/1db5cdb2-a1eb-11e6-8078-c53b0efe354f.gif)

This only seems to occur when inserting immediately after an indentation. 

```
IntelliJ IDEA 2016.2.5
Build #IU-162.2228.15, built on October 14, 2016
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by alexander-doroshko** [comment]
IDE has 'Reformat on paste' setting in Preferences | Editor | General | Smart Keys that is by default set to 'Indent each line'.
In your example code becomes not valid after pasting, so it is not strange that IDE fails to guess correct indent.
You have some options:
- You may set 'Reformat on paste' to 'None'
- Or you may do Paste Simple instead of standard Paste. Shortcut is Cmd+Alt+Shift+V. Such pasting doesn't try to add any smartness.

**Comment by pq** [comment]
Sounds like this is a general IntelliJ behavior and we may just have to train our users.

@lukechurch: thoughts?

**Comment by lukechurch** [comment]
>In your example code becomes not valid after pasting, so it is not strange that IDE fails to guess the indent that you expect. 

I don't really agree. The text I am inserting is opening another clause '('. I don't see how the correct indentation heurestic can be that is should be less indented than the previous clause. That could only happen if I closed the previous clause which would require a ']'.

However, if this kind of behaviour is standard, then yes, we may need to train our users to paste with the different shortcut.

**Comment by devoncarew** [comment]
Discussing this a bit, we think this is an indentation issue.

**Comment by mit-mit** [comment]
@stevemessick would you mind investigating a bit to see if this is our issue, or needs to go to JetBrains?

**Comment by stevemessick** [comment]
While it is indeed an indentation issue, solving it is going to require significant work in the IntelliJ implementation of the Dart parser.

Here's a screen shot of how the parse tree should look, assuming the syntax is correct after pasting "h(1001, ":
<img width="1207" alt="screen shot 2017-02-09 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/8518285/23718822/da11e1f8-03ed-11e7-812f-9c4be3751419.png">

I've selected the "h" identifier and highlighted the associated node in the tree. Note how deep it is. (Actually, I didn't even expand the reference expression fully; the identifier is within it.)

Here's what the same code looks like if (as Luke showed) you paste the string without first inserting the matching close-paren:
<img width="1215" alt="screen shot 2017-02-09 at 2 26 54 pm" src="https://cloud.githubusercontent.com/assets/8518285/23718870/03c9b7dc-03ee-11e7-945c-f78c12dad84a.png">

Note the relatively flat structure surrounding the "h" identifier. Also note the PsiErrorElement for the colon following "children". That marks a parsing error, way above the code that was pasted.

The implementation of auto-indent uses the parser and since the current parser doesn't have really good error correction it will require quite a lot of work to fix this issue. I have to agree with Alex's comment that using the simple form of paste is the best way to solve the problem.

As Phil and Luke suggest, we need better user education. Using Extend Selection along with Surround With Parens could also be useful in this example. Or, defining a Live Template with linked-editing may be the way to go.

**Comment by devoncarew** [comment]
assumed stale -
