### ISSUE TITLE
dartfmt for selection only

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter-intellij#4177]
The context menu has the option `Reformat Code with dartfmt`, but this applies to the whole document. If there's selected code, then dartfmt should only reformat the selected code, same as `Ctrl+Alt+L` does.

**Comment by pq** [comment]
See: https://github.com/dart-lang/dart_style/issues/92

**Comment by feinstein** [comment]
Hmm it's open since 2014, I thought it would be simpler

**Comment by alexander-doroshko** [comment]
@feinstein, the feature is implemented on the IntelliJ IDEA end in the just released 2019.3 version. Well, strictly speaking, `Reformat Code with dartfmt` actions stays the same (reformats the whole file) but you don't actually need this action anymore. Standard `Reformat Code` action (`Ctrl+Alt+L`) calls `dartfmt` under the hood. And since 2019.3 `Ctrl+Alt+L` with selection applies `dartfmt` result for the selection only.

For the reference: https://youtrack.jetbrains.com/issue/WEB-41609

**Comment by feinstein** [comment]
@alexander-doroshko interesting, but earlier today I tried to update to 2019.3 and it says the Dart Plug-in isn't compatible with that version, so I avoided upgrading it.

**Comment by alexander-doroshko** [comment]
Sorry for this glitch. It's just a wrong error message. Of course, there are compatible versions of Dart and Flutter plugins, they will be updated after the IDE update.

**Comment by feinstein** [comment]
Oh OK thanks!
