### ISSUE TITLE
Different behavior for projects created in IJ and in the CLI

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#421]
If you create a new Flutter project in IJ, and you get the template files, and `lib/main.dart` is opened in the code editor.

If you create a new Flutter project in the CLI (using `flutter create`), and then `File > Open` in IJ on that project, nothing is shown in the code editor.

Is this discrepancy intentional?

**Comment by mit-mit** [comment]
Michael to dig up what is missing in .idea

**Comment by mit-mit** [comment]
I cannot entirely figure this out. When we `flutter create`, we end up with the following in `.idea/`:

  * `modules.xml`: Defines the core component
  * `runConfigurations/main_dart.xml`: Defines the core runConfig

When you File > New Project in IntelliJ you get a lot of other files in `.idea/`.

@alexander-doroshko is there some third file we can create with `flutter create` so that `lib/main.dart` is opened in IntelliJ?

**Comment by alexander-doroshko** [comment]
It's not about .idea folder content.
It's just 2 completely different branches in code that work.

- One scenario is New Project Wizard (New Module Wizard is actually the same). You have implemented it for Flutter project via FlutterModuleType, FlutterModuleBuilder, etc. And there you have implemented Flutter Run Configuration creation and main.dart file opening, see `io.flutter.sdk.FlutterSdk.Command.CREATE.onTerminate()`

- Completely different code works on 'Open' action. You didn't add any hooks to it, so you get neither run configurations, nor open editor. There's a number of hooks available for plugins, like `ProjectOpenProcessor` and others. You may track the whole path by setting a breakpoint in `com.intellij.ide.actions.OpenFileAction#doOpenFile`.

The problem is also tracked as #316

**Comment by mit-mit** [comment]
Ah, yes, failed to make that connection, thanks!

Closing this and added a note in 316.
