### ISSUE TITLE
Incorrect FPS in Flutter Performance Window for Flutter desktop (macos)

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#4255]
FPS reported at -0.0.

![Screen Shot 2019-12-19 at 4 14 26 PM](https://user-images.githubusercontent.com/43759233/71839491-2006ac00-3070-11ea-9ab0-8f8f753dd8cf.png)

**Comment by devoncarew** [comment]
This was possible against a Flutter Desktop device (macos)?

**Comment by kenzieschmoll** [comment]
@liyuqian calling the `_flutter.getDisplayRefreshRate` extension for flutter desktop (macos) is returning 0.0. Is there an issue tracking this?

**Comment by liyuqian** [comment]
@kenzieschmoll : I don't think so. It's returning 0.0 because the relevant function isn't properly implemented on macos. Please feel free to create an issue and maybe assign it to someone working on Flutter desktop.

An implementation would look like https://github.com/flutter/engine/commit/4c4c9997780a698bbb3ce3319af6eb07e910681d or https://github.com/flutter/engine/commit/2bd75ae8bae541e4d5413f1715ff3a8b99d1dffe

**Comment by kenzieschmoll** [comment]
Flutter issue filed here: https://github.com/flutter/flutter/issues/49222
