### ISSUE TITLE
How to create dart statement?

### ISSUE THREAD

**Issue by moodi1999** [flutter/flutter-intellij#4329]
i know this not the right place for asking this question but i couldn't find somewhere more related to dart psi than here.
i asked my question in [stack Overflow](https://stackoverflow.com/questions/59801546/how-to-create-a-new-statement-in-dart-with-intellij-dart-plugin) , still no answer.☹
i could ask this in dart intellij plugin but as i cloned this repo, i though it would be better to ask here. thanks🙏

**Comment by devoncarew** [comment]
Hi @moodi1999, I'd review the general dart documentation at dart.dev (like https://dart.dev/guides/language/language-tour).

**Comment by moodi1999** [comment]
@devoncarew i think i asked my question in a bad way.
i mean't create it with dart plugin , 
as i asked here : [stack Overflow](https://stackoverflow.com/questions/59801546/how-to-create-a-new-statement-in-dart-with-intellij-dart-plugin) 

`final PsiElementFactory factory = JavaPsiFacade.getInstance(project).getElementFactory();
PsiStatement useMemoStatement = instance.createStatementFromText("int a = plus(b + c);", null);
`
in java we can create a statement like above. i cloned flutter plugin and i'm adding a new intention(alt + enter) function, but idon't know how to create new statement in dart.

flutter dart intellij-plugin intellij-platform-psi

**Comment by devoncarew** [comment]
Ah, gotcha.

@jwren and @alexander-doroshko are more familiar with how to create a new Dart statement with PSI elements.

Note however that much of the code to manipulate Dart code is implemented in the analysis server. Depending on the type of functionality, we may prefer the implementation in a different part of the system.

Perhaps open an issue to discuss the use case?

**Comment by alexander-doroshko** [comment]
@moodi1999 you may look at the `DartElementGenerator` class and its usages in the [Dart plugin source code](https://github.com/JetBrains/intellij-plugins/tree/master/Dart).

However, note that the canonical way to provide an intention action is to do it on the Dart Analysis Server end. All existing intentions (as well as quick fixes, completions, and many more) come from the Analysis Server. It is possible to write a plugin for the Analysis Server that would contribute more intention actions. 

Also, I guess if your idea is useful enough for a lot of users you may ask to add the required intention action right to the Analysis Server, so that everyone gets it out-of-the-box.
