### ISSUE TITLE
Flutter co-editing features not present in existing project

### ISSUE THREAD

**Issue by xster** [flutter/flutter-intellij#4433]
Open https://github.com/flutter/samples/tree/master/add_to_app/android_fullscreen after 'flutter pub get'ing https://github.com/flutter/samples/tree/master/add_to_app/flutter_module. 

After gradle syncs and everything, it will run correctly and bring in the Flutter subproject, but in the IDE, the Flutter parts of the IDE functionalities aren't present

<img width="1034" alt="Screen Shot 2020-03-20 at 11 04 25 PM" src="https://user-images.githubusercontent.com/156888/77220612-264ce600-6aff-11ea-97ef-0d31c0a83007.png">

cc @stevemessick 

I'm on 3.6.1.

**Comment by stevemessick** [comment]
After looking at the `samples/.gitignore`, I'd say this is working as expected. Since the `*.iml` files are not checked in you will have to re-designate all source directories before any indexing can occur. And since the `.idea` folder is not checked in you'll have to re-import all modules not brought in by the gradle script. I'm not sure what effect eliminating `.vscode` will have.

The existence of `android_fullscreen/.gitignore` is confusing. It looks like specific files in `.idea` are meant to be ignored, but there's no `.idea `in the repo, probably due to the rule in the root `.gitignore`.

IIRC when we import a module we have to change something in its `.android`. So having `.android` in `flutter_module/.gitignore` is probably going to break it.

For the plugin sources we include specific files in `.idea` that should be ignored in [our .gitignore](https://github.com/flutter/flutter-intellij/blob/master/.gitignore). (And we don't check in our modules for the reason that most people only use one. I use several.)

**Comment by xster** [comment]
Thanks for diving into this. I suppose what this means is that if the user followed the manual integration steps in https://flutter.dev/docs/development/add-to-app/android/project-setup#manual-integration, they need to retrace the module import wizard flow in the IDE to get co-editing. Is that right? In that case, we could add some more hints to https://flutter.dev/docs/development/add-to-app/android/project-setup. 

This might also be a question for @RedBrogdon. Should the default samples have the various intellij metadata checked-in? So someone can just clone the repo, AS open the host project and see both projects.

**Comment by RedBrogdon** [comment]
> The existence of android_fullscreen/.gitignore is confusing. It looks like specific files in .idea are meant to be ignored, but there's no .idea in the repo, probably due to the rule in the root .gitignore.

That's a good catch. The repo was originally set up with the assumption it would contain only Flutter projects, and the .gitignore reflects that. I've been meaning to yank it out in favor of individual ignores in each project, and it sounds like I need to get on that.

For Flutter projects, we do try to be IDE agnostic. To clarify for Android projects, though, is it considered standard policy to check in some of the Android Studio configuration files?

**Comment by stevemessick** [comment]
@RedBrogdon JetBrains has some advice:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Also see the .gitignore I linked in my previous reply.

I'd recommend including IDE-specific files for all supported IDEs. That would make samples more useful with less fuss.

@xster I still need to follow-up for you. Not forgotten, just busy.

**Comment by stevemessick** [comment]
@xster you need to switch your Project view from Android to Project or Project Files.

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/4479

Remember to switch the project view to Project or Project Files!
