### ISSUE TITLE
Option to break on handled exceptions in Flutter framework

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#462]
_From @sethladd on January 29, 2016 18:29_

_From @sethladd on January 12, 2016 17:5_

Was: https://github.com/dart-atom/dartlang/issues/630

Flutter handles most (all?) exceptions thrown from user code. This is usually pretty great, except when I'm debugging. I want my app to stop at the point of the exception, so I can work on fixing it.

Normally, the editor can break on unhandled exceptions. But for handled exceptions, we might need to do something "Flutter aware".

_Copied from original issue: flutter/atom-flutter#31_

_Copied from original issue: flutter/flutter#1476_

**Comment by mit-mit** [comment]
_From @Hixie on January 29, 2016 18:45_

We could create a `debugBreakOnException` boolean in some low-level file and then have the various exception-catching methods call:
```dart
debugger(when: debugBreakOnExceptions);
```

**Comment by mit-mit** [comment]
_From @Hixie on January 29, 2016 18:46_

(and expose `debugBreakOnExceptions` as an extension that Atom can set)

**Comment by mit-mit** [comment]
_From @eseidelGoogle on May 13, 2016 17:14_

I'm not sure what this asking for.  @devoncarew added the ability to have Atom break on all exceptions, did that solve this?

**Comment by alexander-doroshko** [comment]
VM Service protocol allows to choose how to stop on exceptions: All, Unhandled or Node. Default in IntelliJ is Unhandled. I think an option in the IDE should be added to allow user to choose. Tracked as https://youtrack.jetbrains.com/issue/WEB-13268

**Comment by mit-mit** [comment]
@johnmccutchan to talk to Flutter team about this to understand if `All` might be too "noisy". Alternatively, have the Flutter framework somehow communicate the event.

**Comment by Hixie** [comment]
With very, very few exceptions, Flutter doesn't use exceptions for flow control -- every exception is a real exception. The problem is that you want to stop the IDE on the line that threw the exception, and simultaneously you want to continue the program to let the framework collect all the information to display its full message (which happens much later).

So the problem isn't that "all" is too noisy, it's that "all" isn't noisy enough. :-)

**Comment by jacob314** [comment]
<img width="619" alt="screen shot 2019-03-06 at 12 02 01 am" src="https://user-images.githubusercontent.com/1226812/53865112-1a998a80-3fa3-11e9-83e3-d8b306918040.png">
This is now supported. 
Note that as described elsewhere, most users don't want to actually pause on exceptions in the framework and this is a bug reason users typically choose the "run" option instead of "debug" in IntelliJ.
