### ISSUE TITLE
moving a list element

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#464]
_From @HansMuller on February 19, 2016 0:16_

If I had a nickel for every time I moved elements of a Dart list around and forgot to fix up the commas.

In the example below, it would be nice if one could put the cursor within the "new Flexible(...)" statement, hit a magic key several times - moving the scope of the selection outward - until the entire new Flexible() list element was selected. Then, with a different magic key, move the list element elsewhere in the list.

```dart
  children: <Widget>[
    new Text(destination.description[0], style: descriptionStyle),
    new Text(destination.description[1], style: descriptionStyle),
    new Text(destination.description[2], style: descriptionStyle),
    new Flexible(
      child: new Row(
        justifyContent: FlexJustifyContent.start,
        alignItems: FlexAlignItems.end,
        children: <Widget>[
          new Padding(
            padding: const EdgeDims.only(right: 16.0),
            child: new Text('SHARE', style: buttonStyle),
          ),
          new Text('EXPLORE', style: buttonStyle),
        ],
      ),
    ),
  ]
```

_Copied from original issue: flutter/flutter#2017_

**Comment by stevemessick** [comment]
The IntelliJ _Move Statement_ command has been repurposed to accomplish this.

https://github.com/JetBrains/intellij-plugins/pull/473

**Comment by devoncarew** [comment]
🎉 !

(cmd-shift-up and cmd-shift-down, for those following along)

**Comment by mit-mit** [comment]
Will this require a new IJ roll, or just a new Dart plugin?

**Comment by pq** [comment]
@devoncarew and I were playing with this and it doesn't seem to work well with reordering list items.

@stevemessick is this still in progress?

**Comment by stevemessick** [comment]
@pq Always. Fixing bugs is a never-ending task. This particular code is very complex. That said, if your code wasn't formatted by dartfmt using trailing commas everywhere then it is expected to fail.

Add examples here or file new bugs. Or just catch me in the office :)

**Comment by pq** [comment]
Happy to chat in the office.  In the meantime, try this one from [`cards_demo.dart`](https://github.com/flutter/flutter/blob/master/examples/flutter_gallery/lib/demo/material/cards_demo.dart):

```dart
            new Expanded(
              child: new Padding(
                padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 0.0),
                child: new DefaultTextStyle(
                  softWrap: false,
                  overflow: TextOverflow.ellipsis,
                  style: descriptionStyle,
                  child: new Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      // three line description
                      new Text(destination.description[0]),
                      new Text(destination.description[1]),
                      new Text(destination.description[2]),
                    ],
                  ),
                ),
              ),
            ),
```

Try moving one of the `Text` and things get pretty funky.

**Comment by stevemessick** [comment]
Works fine when I do it. Perhaps you can give me a demo.

TBH I'm not sure that code is available outside the EAP release. It is part
of the Dart plugin.

**Comment by HansMuller** [comment]
I was just talking with @pq and @devoncarew about this feature request. I'm probably confusing things, but it seemed as though its implementation was asking the analyzer to do something very difficult, due to intermediate states introduced by pushing a widget upwards in the hierarchy.   That's definitely not what I was asking for. Just in case there's any confusion, here's what I was after.

The user puts the cursor within the new Text ... 'SHARE' expression and presses some key that means expanded the select to the containing expression (I imagine IJ can already do this).
![screenshot0](https://cloud.githubusercontent.com/assets/1377460/23774952/1ef69424-04db-11e7-8790-d191f6b3a03a.png)

Hitting the expands-outwards key a few more times selects the 3rd element of the Widget list:
![screenshot1](https://cloud.githubusercontent.com/assets/1377460/23775039/803e898a-04db-11e7-8e4d-009c8ec7b53d.png)

Now our goal is to move the selected expression around in the Widget list that it's contained in.  Pressing some other "up" key moves the entire Flexible expression up one list position.
![screenshot2](https://cloud.githubusercontent.com/assets/1377460/23775222/7a1a8e68-04dc-11e7-9344-93c9d15b34af.png)

For the record, this was more painful to do by hand when I first asked for the feature, because trailing commas were not allowed.

**Comment by stevemessick** [comment]
@HansMuller Thanks! That's been implemented, but it is not in the analyzer. I piggy-backed on the IntelliJ Move Statement functionality that is in the Dart plugin.

Alt-UpArrow does expand the selection to the next level of syntactic structure. But you don't have to select anything; you could just click on 'Flexible' and not select anything to use Move Statement to move the new-expression up or down the list.

I didn't realize this request pre-dated trailing commas. Yeah, would've been a lot more tricky then.

There are also completely different functions, implemented in the analyzer, to wrap a new-expression with another new-expression (re-parenting), and to move widgets up and down the hierarchy. The latter is the one I'm most interested in improving by making it available in more contexts, if that's appropriate.

**Comment by pq** [comment]
> Works fine when I do it. Perhaps you can give me a demo.

Confirmed that this works in the EAP 👍
