### ISSUE TITLE
analysis_options exclude doesn't work

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4643]
```
  exclude:
    - "lib/helpers/viet_calendar.dart"
```
but still get warning
<img width="1159" alt="Screen Shot 2020-06-22 at 5 52 02 PM" src="https://user-images.githubusercontent.com/52562340/85279734-1f908f00-b4b1-11ea-99b0-b2aba7af2620.png">

from https://github.com/flutter/flutter/issues/59976

**Comment by pq** [comment]
See also: https://github.com/dart-lang/sdk/issues/35475.

/fyi @bwilkerson @jwren

**Comment by bwilkerson** [comment]
This is a long-standing issue and part of the reason it hasn't been "fixed" yet is that it isn't clear what "fixed" means.

When a file is excluded from analysis it means that the analysis server won't send back any diagnostics associated with that file. (It won't even open the file unless there's a need to do so in order to analyze a non-excluded file). The problem arises when the user later opens the file. At that point we have two choices: either we continue to hide the diagnostics or we display them. If we hide them, then some users are confused because all of the other IDE features work and they assume that the absence of diagnostics means that the file analyzed cleanly when it didn't. If we display them, then some users are confused because they asked us to exclude the file from analysis.

Which is the better failure mode?

**Comment by tbm98** [comment]
is it means analyze will not show warning about this file if I don't open it ? @bwilkerson

**Comment by bwilkerson** [comment]
That should be the current behavior, yes. If that's not what you're seeing, then we have a different issue.

**Comment by stevemessick** [comment]
The analyzer should have an option to suppress warnings on excluded files.
Optionally, change the error message to to be more informative.

**Comment by tbm98** [comment]
I'll feedback if it have any problem
