### ISSUE TITLE
Highlighted thing is not showing in my suggestion When I clicked material colors. Many of said that this issue was reported but still it not changed.. 

### ISSUE THREAD

**Issue by Denesh-Jaden** [flutter/flutter-intellij#4661]
[Thanks](url) for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter
<img width="1406" alt="Screen Shot 2020-06-26 at 8 33 43 PM" src="https://user-images.githubusercontent.com/64740667/85873280-8635e580-b7ee-11ea-9051-a309c829fd44.png">
/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by SadSack963** [comment]
I was passed to this issue repo by @TahaTesser from <https://github.com/flutter/flutter/issues/59132> since it seems this is a plug-in issue.

It looks like that feature has been removed (accidentally?) in the latest Flutter Plugin (or is it Android Studio 4?)

It currently doesn't work on my Windows 10 machine, so I installed an old version of Android Studio on my Linux VM with Flutter Plugin 39.0.1, and the pop-up worked just fine (Ctrl+Q).

However, after upgrading Android Studio, (and Flutter/Dart) it no longer works. I should make that clearer: the Quick Docs pop-up still works (Ctrl+Q) but the palette is no longer shown on the pop-up.

The differences between a working pop-up and a non-working pop-up are the upgrades:
Android Studio: 3.4.2 -> 4.0
Flutter Plugin: 39.0.1 -> 46.0.2
Dart Plugin: 183.6270 -> 193.7361
Both tests used Flutter version 1.17.3.

The palette does still work in Visual Studio Code tested on Windows 10 - but not in Android Studio tested on Windows 10 and Linux Mint. Maybe the VS Code extension isn't quite as up-to-date as the Android Studio plug-in?
![84604198-2fdeb380-ae8c-11ea-91b2-a14640eb89c9](https://user-images.githubusercontent.com/60894773/86234547-02358200-bb8f-11ea-8017-7f54b6eff78b.png)
![84604195-2ead8680-ae8c-11ea-94b4-b43a2a8daad1](https://user-images.githubusercontent.com/60894773/86234582-12e5f800-bb8f-11ea-95df-aeac8c566ead.png)
![84604194-2d7c5980-ae8c-11ea-9313-4827c41f5768](https://user-images.githubusercontent.com/60894773/86234593-1a0d0600-bb8f-11ea-9d3f-1e6d220efce7.png)
![84604191-25bcb500-ae8c-11ea-9ed1-a6a140e7e256](https://user-images.githubusercontent.com/60894773/86234604-1e392380-bb8f-11ea-9bd0-19921968d1a7.png)
![85934464-b3f85880-b8da-11ea-9d35-b9675c19d7fd](https://user-images.githubusercontent.com/60894773/86234641-2abd7c00-bb8f-11ea-8989-c1d7a2bf5b7e.png)






flutter doctor -v
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.18362.295], locale en-GB)
    • Flutter version 1.17.4 at E:\Flutter
    • Framework revision 1ad9baa8b9 (2 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at D:\Users\John\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at D:\Users\John\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by stevemessick** [comment]
@devoncarew do you know who is most familiar with the Flutter-specific color completion support?

@SadSack963 just wanted to say thanks (again) for all the information.

**Comment by crzaratech** [comment]
I'm following a flutter tutorial and in the video it showed, and I didn't have it. Not as important just annoying that I don't have it :p  Still haven't found the fix, I updated Android and flutter today. Have tried pretty much everything up to this point. Don't know if its still an issue going to keep looking

Dart Plugin 193.7361
Flutter Plugin 48.1.2

https://user-images.githubusercontent.com/54729832/90309086-9e4eea80-deaa-11ea-96c1-bd166a9034c3.png
![image](https://user-images.githubusercontent.com/54729832/90309095-c4748a80-deaa-11ea-80d6-cde129283608.png)

![image](https://user-images.githubusercontent.com/54729832/90309123-10273400-deab-11ea-9bc0-56bae8292dac.png)
![image](https://user-images.githubusercontent.com/54729832/90309137-33ea7a00-deab-11ea-8501-a9ee882b235d.png)

**Comment by crzaratech** [comment]
Update! I just got it to work, this is what i did:
I followed this post:
 https://stackoverflow.com/questions/62017394/flutter-not-showing-list-of-color-swatches-for-colors-in-android-studio/62049796#62049796
but when I try manually installing the dart plugin like he does, i would get an error saying its not compatible. 
So I looked at my Android Studio build then copied the build and did a ctrl+F in JetBrain's plugin and installed the latest version for my build: https://plugins.jetbrains.com/plugin/6351-dart/versions/

before:
![image](https://user-images.githubusercontent.com/54729832/90310316-1f5faf00-deb6-11ea-87e9-eda73049a544.png)

I tried different versions in between, that's why initial build version is different. But 193.7361 is the one that fixed the issue for me.
![image](https://user-images.githubusercontent.com/54729832/90310396-ab71d680-deb6-11ea-8309-53a051eb4fce.png)
![image](https://user-images.githubusercontent.com/54729832/90310457-04da0580-deb7-11ea-9ed0-d4c8e5617fe0.png)

**Comment by stevemessick** [comment]
@alexander-doroshko was removing the color panel intentional? It looks like a bunch of people miss it.

**Comment by alexander-doroshko** [comment]
I see`MarkdownUtil.removeImages()` line in `DartDocUtil` class in [the Dart plugin sources](https://github.com/JetBrains/intellij-plugins/blame/0f1c8814311742d8d4d1afaceaaa1caa385c6ca8/Dart/src/com/jetbrains/lang/dart/ide/documentation/DartDocUtil.java#L183). It removes images from the documentation popup. I verified that colors preview are back without this line of code.

@jwren Do you remember if `MarkdownUtil.removeImages()` was intentional and what was the purpose of this line?

**Comment by alexander-doroshko** [comment]
Images preview in the documentation popup has been restored in the latest update of the Dart plugin. Thanks for reporting.
