### ISSUE TITLE
update the flutter-intellij repo to pull its flutter metadata from tool_metadata

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#4720]
We should update this repo to pull its flutter framework metadata from https://github.com/flutter/tools_metadata (instead of generating it in this repo).

**Comment by DanTup** [comment]
I think my comment against the commit was misleading - the format hasn't changed in the new files - I just noticed it was different to HTML/CSS and wasn't sure if that was an oversight.

Since it's not uncommon to write colors in Flutter as hex values (`Color(0xAARRGGBB)`) I think we should leave things as-is and just document in the tools_metadata repo the format they are in.

**Comment by DanTup** [comment]
PR with a note here -> https://github.com/flutter/tools_metadata/pull/17
