### ISSUE TITLE
AVD manager does not show up in tools menu within Android Studio

### ISSUE THREAD

**Issue by hp685** [flutter/flutter-intellij#5145]
## Steps to Reproduce

I created a project following along the tutorial here: https://flutter.dev/docs/get-started/test-drive
However target selector shows no devices and according to a linked article, I should enable it from the tools menu by selecting AVD manager. The issue is that tools menu does not have an AVD manager option. I was eventually able to find  the AVD manager using CTRL-SHIFT-A and typing in avd manager. Clicking on it does nothing for me

## Version info
/home/livelypanda2020/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel beta, 1.25.0-8.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.25.0-8.1.pre at /home/livelypanda2020/flutter
    • Framework revision 8f89f6505b (6 days ago), 2020-12-15 15:07:52 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/livelypanda2020/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by helin24** [comment]
I think this may be an issue with Android Studio setup, because we don't control the AVD manager. Do you have devices with non-Flutter projects?

There are some steps mentioned here to troubleshoot missing AVD manager: https://stackoverflow.com/questions/47173708/why-avd-manager-options-are-not-showing-in-android-studio

**Comment by hp685** [comment]
I figured out that this is because I'm running the android studio on a pixel slate and as I understand pixel slate doesn't yet support emulators - is that right?

**Comment by helin24** [comment]
@hp685 I'm not familiar with this system, so I can't say for sure. It looks like from this article that emulators may not be supported - https://www.aboutchromebooks.com/news/some-chromebooks-now-support-the-android-emulator-for-developers/

Closing this issue since it isn't something we oversee. If you have further questions about this it may make more sense to contact Android Studio support.
