### ISSUE TITLE
Drag and drop file from one folder to another folder generate absolute import path on android studio (Only Windows)

### ISSUE THREAD

**Issue by shofizone** [flutter/flutter-intellij#5271]
**Drag and drop** file from one folder to another folder generate **absolute import path** on **Android Studio** in **only Windows 10.** While using **MAC** I didn't find such kind of issue. This only happens while drag and drop file. Some time it prompts "do refactor" but result is same. 
**Expected**: import 'package:example_app/pages/compress_settings_page.dart';
**Actual** : import 'file:///G:/WorkSpace/example_app/lib/pages/compress_settings_page.dart';

**Comment by stevemessick** [comment]
@alexander-doroshko Do you know where drag-drop file moving is implemented? It seems like something the Dart plugin would do, but I couldn't find the code.

**Comment by alexander-doroshko** [comment]
@stevemessick I can reproduce the issue and I can confirm this is an Analysis Server bug.
(For technical details see [DartServerMoveDartFileHandler](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/refactoring/moveFile/DartServerMoveDartFileHandler.java) and [MoveFileRefactoring](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/ide/refactoring/moveFile/MoveFileRefactoring.java) classes in the Dart plugin source code.

This issue is already tracked as https://github.com/dart-lang/sdk/issues/43602, https://github.com/dart-lang/sdk/issues/41947, and https://github.com/dart-lang/sdk/issues/41889. I'd love to have it fixed.

**Comment by stevemessick** [comment]
Thanks @alexander-doroshko ! `MoveFileHandler` is the refactoring service I was looking for.
