### ISSUE TITLE
make sure that the different ways to open a project are covered by the Flutter plugin

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#530]
So, things like:

- [ ] File > New > Project 
- [ ] File > New > Project from existing sources
- [ ] File > Open

We have this tracked in some individual items, but we should make sure that all our bases are covered.

**Comment by pq** [comment]
### File > New > Project

Creating a new Flutter project adds flutter module type (and enables Dart) as expected.

Happy path. 😄 

### File > New > Project from existing sources

Existing Flutter projects get coerced into being Android projects (with just an android folder content root --- no Dart sources). 😦 

![screen shot 2016-12-13 at 2 04 07 pm](https://cloud.githubusercontent.com/assets/67586/21161355/0eb67214-c13d-11e6-9542-1a61da8e2fd4.png)

(That said, I'm not even convinced these are fully functioning android projects either.)

Getting this working likely involves hooking project import via one of the project import extension points.

**NOTE:** this action is generally designed to support importing from other project definitions such as eclipse or gradle:

![screen shot 2016-12-13 at 2 07 55 pm](https://cloud.githubusercontent.com/assets/67586/21161456/89b7c1e8-c13d-11e6-8103-3adab4be2f16.png)

We'd fall under "unspecified origin" and though it should work ideally it may be a bit of work since we'd have to compete with the Android-savvy importer.  Maybe we can just document this as a known limitation?


### File > Open

Opening a Flutter project with metadata works as expected.

Creating a project (`flutter create`) and opening, yields a project without Flutter enabled but with a butter bar option to enable it.

![screen shot 2016-12-13 at 2 15 49 pm](https://cloud.githubusercontent.com/assets/67586/21161757/c974c9ce-c13e-11e6-80a4-40c24b71e0f5.png)

Once enabled things work as expected.

**Comment by devoncarew** [comment]
1) - awesome!


2) - we should document this limitation and file an issue to track, prioritize, and likely, eventually fix it

3) - I had thought that we were creating all the metadata necessary for fully-formed IntelliJ projects? Any idea what we're missing here - why we see the butter-bar and it's not just opening as a flutter project?

**Comment by devoncarew** [comment]
re: 3) above, when I ran `flutter create`, then did a `File > Open` in IntelliJ, it opened fine - I didn't see a butter bar.

**Comment by pq** [comment]
RE: 2) tracking issue here: #542

RE: 3) I updated flutter and now can't repro so I think we may actually be good after all -- sorry for the noise!

Optimistically closing this in favor of following up on the **File > New > Project from existing sources** scenario in the new tracking issue (#542).  Feel free to re-open as you see fit!

**Comment by pq** [comment]
Update: closed #542 which duplicates #316.
