### ISSUE TITLE
Flutter inspector not working

### ISSUE THREAD

**Issue by dhirajhimani** [flutter/flutter-intellij#5378]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

IntelliJ IDEA 2021.1 • Flutter plugin io.flutter 55.0.5 • Dart plugin 211.6693.108

Error getting Flutter sdk information.

## Version info

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

**Comment by helin24** [comment]
Is your issue the same as https://github.com/flutter/flutter-intellij/issues/5376? If not, we need some more details on what happened and any errors logged to your console.

**Comment by azeek** [comment]
And also the breakpoint is not working.

**Comment by helin24** [comment]
@azeek we'll need more details on your problem(s) - things that could be helpful:
- screenshots of the inspector issue or debugging breakpoint not working?
- details about the steps you're taking to run your app when debugging breakpoint fails
- `flutter doctor -v` output

Also I recommend updating your flutter plugin to v55.1; I can't tell if the inspector issue originally described is due to an incompatibility for 2021.1 and mac. You should see an option to update if you go to Preferences > Plugins.
