### ISSUE TITLE
Code completion doesn't jump to the the item already there

### ISSUE THREAD

**Issue by lukechurch** [flutter/flutter-intellij#544]
E.g. select the gallery example, select 'Card' and request a code completion

![image](https://cloud.githubusercontent.com/assets/2978182/21188899/bf9d6c5e-c214-11e6-8396-02ccb012e697.png)

It should jump to 'Card' being selected from the list so I can look at the documentation. I don't understand why 'Expando' is the first item, and the out one out of alphabetical order.

**Comment by alexander-doroshko** [comment]
I believe `Expando` is the first in the list because you previously selected it using code completion somewhere else. At the top of the list there are the most frequently used items, then others go alpha-sorted.

`Card` is not focused in the completion list because caret is before `Card` word in the code. So there's no prefix to match. If you put caret after `Card` then the focused item will be different.

BTW to see documentation you can press F1 without invoking code completion at all.

So far I do not see any bugs to fix.

**Comment by lukechurch** [comment]
@sethladd

**Comment by lukechurch** [comment]
@alexander-doroshko Ah, I see, it does prefix matching.

The problem here is that the current behaviour interferes with a pretty common use case of having selected one completion, deciding it didn't need their needs, and resuming looking in the list for other options. Until your description I would not have thought of clicking after the 'card' text to resume searching. The re-orientation into 'where you were' is fairly important in this context.

It also interferes with the 'what did the UI tell me that I needed to know about card again?' interaction. This happens when people are e.g. trying to remember the option arguments list that appeared. They got to that piece of UI by performing a code completion request, so it's typical that they will try and return there using the same interaction again.

**Comment by sethladd** [comment]
> At the top of the list there are the most frequently used items, then others go alpha-sorted.

That's very good to know. That helps explain a lot :)

**Comment by alexander-doroshko** [comment]
One more hint. Items sorting in the completion has 2 modes: lexicographical and relevance. The current mode is shown in the bottom-right corner of the popup (Greek 'Pi' or Latin 'A'). You can switch mode by clicking it. In lexicographical mode IDE simply does alpha-sort, it doesn't respect priority given by the Analysis Server or frequency of the previous usages.

As for focusing the item that matches text written AFTER caret: this decision is neither in scope of Flutter nor Dart plugin. You may file a request to change IntelliJ IDEA's core completion engine. Though core guys may have their own opinion on the problem.

**Comment by mit-mit** [comment]
> cc @sethladd for his thoughts, I know that he has been interested in improving the code completion UX recently

Luke, we are working on a larger initiative to improve editing in Q1; there is a raw list of candidates here: https://github.com/flutter/flutter-intellij/labels/topic-editing

**Comment by mit-mit** [comment]
> E.g. select the gallery example, select 'Card' and request a code completion

@lukechurch, I am curious, how did you end up with the caret right before `Card` as part of selecting it? I experimented a bit myself and whether I used the mouse of keyboard I could not come up with a way where it did not end up either in the word or right after it -- and in all those cases, completion does the right thing.

**Comment by mit-mit** [comment]
@alexander-doroshko actually one case seems odd: if you double click `Card` if select it and places the caret right after the work. If you then invoke complete, it ignores the `Card` prefix and thus behaves differently than when you place the caret right after `Card` with the keyboard. Why is that?

**Comment by alexander-doroshko** [comment]
Interesting :). I never noticed it in 13 years of coding in IntelliJ IDEA. Probably I never mixed selection and completion, I can't think out a real use case that would lead me to this situation.

Though I thought a bit and find this behavior reasonable. Selecting item from completion list is an editor action similar to typing a word. When you have any selection and start typing - selection is removed and substituted with what you type. And the same happens when you pick an item from the completion list: if there is any selection - it is substituted with the picked item. That's why it makes no sense to check prefix matching when the prefix is selected - it will be overwritten anyway. I believe it is done by design.
