### ISSUE TITLE
Completions should *not* be case sensitive

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#552]
*Repro steps*:

1. Create a new Flutter project in IJ
1. In `main.dart` in line 77, delete `new Text(config.title)`
1. Type `tex`

*Expected result*: 
  - Editor suggests `Text` completion

*Actual result*: 
  - Editor suggests just completions matching `tex` starting with a lower-case T

**Comment by mit-mit** [comment]
It's worth nothing this is different from just about any other IDE I can think of (xCode, VS, etc.)

**Comment by alexander-doroshko** [comment]
It is neither in scope of the Flutter nor Dart plugin. It is IDE-level setting that you can change as you like. I'm sure people from the core team are not going to change defaults.
![image](https://cloud.githubusercontent.com/assets/4499789/21226588/32b49bfe-c2e7-11e6-8650-09d1c892ba0e.png)

**Comment by mit-mit** [comment]
>  It is IDE-level setting that you can change as you like. I'm sure people from the core team are not going to change defaults.

I understand. Would it be possible for us to ship a "recommended settings" file that could contain the options we recommend for Flutter developers, somewhat similar to a `.keymap` file just for general settings?

**Comment by alexander-doroshko** [comment]
The golden rule for all plugins is that the presence of a plugin must not affect user experience when user is not working with the technology supported by the plugin.

Example: Dart style guides recommends to use line margin at 80 chars. IntelliJ's default is 140. But in this case we were lucky because it appeared to be possible to set line margin per file type. So Dart plugin sets 80 for Dart files and doesn't touch IDE global default.

As for case sensitive completion -  it is not set per file type or per module type. It is global setting. So Flutter plugin must not change the defaults.

And in fact I do not think that there are strong arguments to change the defaults here. We have 16 years of experience and 1,000,000+ of users, and according to own experience, user feedback, and our anonymous statistics most of users are happy with the defaults.

And I myself am very much happy with the defaults. I always know whether I want to write a class name or a method name. So to get smaller completion list I start typing with the correct case. If I have no idea what I want to type and want to see variants I invoke completion without any prefix and get all variants.

**Comment by mit-mit** [comment]
I think you misunderstod my suggestion.

I agree that the current default is probably quite reasonable for exiting IntelliJ customers that become Flutter developers.

What I was suggesting was for new Flutter developers that have *never used InteliJ prior to starting with Flutter*, we could provide a "suggested settings file" they could import. Yes, this would take affect for all of IntelliJ, but again this would be intended for new developer not already using IJ.

**Comment by alexander-doroshko** [comment]
I haven't heard of such possibility. And I do not think JetBrains would like to introduce it. Training newcomers differently depending on the door they came in... I think JetBrains would rather prefer to be opinionated here with the defaults, still allowing users to configure IDE themselves.
