### ISSUE TITLE
Code completion should insert placeholders for `@required` parameters 

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#553]
*Repro steps*:

1. Create a new Flutter project in IJ
1. Delete `new Text(
          'Button tapped $_counter time${ _counter == 1 ? '' : 's' }.',
        )` in line 80
1. Type `new Pad` and complete to Padding

*Expected result*: Editor completes:
```
child:
```
 to:
```
child: new Padding(
  padding: ,
),
```
thus making it clear that a `padding` argument is required.

*Actual result*: Editor completes to just `new Padding()`

**Comment by eseidelGoogle** [comment]
This feature sounds like a great carrot to encourage dart package authors (and flutter framework authors) to annotate @required correctly. :)

**Comment by devoncarew** [comment]
Not sure if there's an is an issue for the associated quick-fix for this -

**Comment by pq** [comment]
> Not sure if there's an is an issue for the associated quick-fix for this -

Quick-fixes landed last week.

<img width="377" alt="screen shot 2017-02-19 at 10 59 34 am" src="https://cloud.githubusercontent.com/assets/67586/23105343/a940dd3a-f692-11e6-845e-6205647391e3.png">

🤘 

Hope to dig into completions this week.

**Comment by pq** [comment]
A little refinement to the proposal.

Instead of:

```dart
child: new Padding(
  padding: ,
),
```

I think we want:


```dart
child: new Padding(
  padding: null,
),
```

since it will parse cleanly.

**Comment by mit-mit** [comment]
That sounds right. And then the Flutter framework should be updated to mark child `@required` so that the expansion becomes:

```dart
   child: new Padding(
     padding: null,
     child: null,
   ),
```

**Comment by pq** [comment]
As of https://github.com/dart-lang/sdk/commit/cc0036d5ad46793b9399443f4d62e3a4c1680320, support is in place on the DAS side.  Once https://github.com/JetBrains/intellij-plugins/pull/495 lands, completions in IDEA will go from a proposal like this

![screen shot 2017-03-02 at 1 13 05 pm](https://cloud.githubusercontent.com/assets/67586/23527253/10700cf0-ff4a-11e6-94e8-cb39057a8bc3.png)

to generated code like this

![screen shot 2017-03-02 at 1 13 17 pm](https://cloud.githubusercontent.com/assets/67586/23527254/10706e0c-ff4a-11e6-9ceb-d5924d1f3dd2.png)

(Note that `x`, `y` and `null` are linked edits and you can TAB between them.)

FYI @sethladd

**Comment by sethladd** [comment]
Um, that's awesome. Nice work!

**Comment by mit-mit** [comment]
Oh, this looks super awesome!

**Comment by devoncarew** [comment]
Very cool!

**Comment by pq** [comment]
As of https://github.com/dart-lang/sdk/commit/f33d072d915e945386762767bf2741fa4a996eaf, completion on `Padding` looks like:

<img width="458" alt="screen shot 2017-03-15 at 4 24 14 pm" src="https://cloud.githubusercontent.com/assets/67586/23975071/fece4f14-099b-11e7-8702-1ae57214f3cc.png">

👍 

The relevant framework bits in IDEA landed in https://github.com/JetBrains/intellij-plugins/commit/314c62ae7172d9a0c99e0f96ea515ee2ae7f8908, and will be available in the next release of the Dart Plugin.

There's a continuing discussion of the treatment of non-required but possibly still desirable boiler-plate generation in #463.

_Note that getting the required analysis bits into Flutter is gated by https://github.com/flutter/flutter/issues/8812._

Since this is just gated by updates upstream, closing here.

**Comment by sethladd** [comment]
Very cool!

**Comment by tolotrasamuel** [comment]
@pq  I have the latest Dart and Flutter plugin on Android studio but the code completion does not place cursor on null, it just sets it to null.
