### ISSUE TITLE
Make unit test name matching more strict

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#5650]
When running tests by name, all tests that match a name will be run. This is fine if the user configures it that way in a run config, but when starting a test by clicking the run symbol next to the test name (in the gutter) it should only run one test. In this case we should change the test name to a pattern that exactly matches one test.

See https://github.com/flutter/flutter/issues/86659

**Comment by DanTup** [comment]
(I don't know if this is relevant here as I'm not sure exactly how the testing works in IntelliJ, but as an FYI..)

With https://github.com/flutter/flutter/pull/86701, the format of the test names will change slightly, so that there is a `variant: ` suffix in the name:

<img width="859" alt="Screenshot 2021-07-20 at 09 54 00" src="https://user-images.githubusercontent.com/1078012/126293102-e6a1467a-ddb2-44e1-9c04-27aa433523e8.png">

This will make it easier given only the test name (which can be gotten from the analysis server outline) to run a test from the editor, allowing the `(variant: foo)` part to be optional (my example regex changes are noted in that PR).

**Comment by stevemessick** [comment]
Fixed in #5763
