### ISSUE TITLE
Unable to find bundled Java version

### ISSUE THREAD

**Issue by McClernan** [flutter/flutter-intellij#5705]
I have a MacOS Big Sur 11.4
I installed Flutter, Android Studio, plugins for Dart etc.
When I run flutter doctor I get "x Unable to find bundled Java versions"
Based on advice on various online forums, I've tried reinstalling Android Studio, renaming Android Studio, checking Android agreement confirmations, and adding paths to .zshrc. 

Recently I read the suggestion of switching to older version of Java - I have 1.8.301.09

I thought I'd ask about the issue here, rather than continue to look for the answers from randos on the Internet. 

Anybody here have any thoughts on how to help flutter doctor find bundled Java versions?

Thanks in advance for any advice you can provide.

**Comment by stevemessick** [comment]
I believe that is an error in `flutter doctor`. I just tried it and got the same message. It is looking for the Java runtime that ships with Android Studio and is not finding it. If Android Studio runs then you can ignore the error. If you can build a Flutter app for Android then your Java is installed correctly. If you can't, I'd suggest installing Java 11 -- I'm not sure the Gradle that is shipped with Flutter will work with Java 8 (not saying it won't).

And, since this is a question about the Flutter tool, I'll move it to the correct repo.

**Comment by McClernan** [comment]
This is very helpful - thank you so much!

**Comment by shuimunianhua99** [comment]
the same question
