### ISSUE TITLE
The IDE code completion is more slow on flutter SDK 2.5

### ISSUE THREAD

**Issue by luckysmg** [flutter/flutter-intellij#5761]
My IDE is Idea

I have tried many times.

**When i switch to flutter SDK 2.5,the code completion tip will take more time to come out...
But when I switch to flutter SDK 2.2.3，it come out very quickly....**

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale
    zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] Connected device (3 available)
```

**Comment by jacob314** [comment]
cc @stevemessick

**Comment by stevemessick** [comment]
@jwren Could you look into this? @jacob314 and I were just chatting and realized this is unlikely to be a Flutter plugin issue.

**Comment by jwren** [comment]
Yes, assigned to myself.  I will chat with Brian and figure out what has changed in the completion algorithm to fix this.

**Comment by devoncarew** [comment]
From running this locally on a helloworld flutter app (flutter master; dart plugin 212.4746.57; IntelliJ 2021.2 CE):

- I do see rough wall clock times of ~1s or slightly longer for completions (I did not do exact measurements end-to-end from IntelliJ, but that should be easy enough from the plugin itself)
- completion times are high for the portion of time just in the analysis server; 300-400ms for the first completion after an edit, and 150ms for 2nd and later completions. even without the likely very high decoding time on the IntelliJ side, this is well past our 100ms completion target

Assuming that the end-to-end times come in where I suspect they are, I think it's safe to say that most dart and flutter developers now see completion times above 1 second.

<img width="745" alt="Screen Shot 2021-09-21 at 11 41 39 PM" src="https://user-images.githubusercontent.com/1269969/134296089-3089a62a-7f7a-43d4-b395-db33aa6e1812.png">

**Comment by devoncarew** [comment]
We are only computing and sending back ~3000 results, which while high, doesn't seem too bad (I was expecting high decoding costs due to 5k-10k results or something). It would be worth looking at what's being sent back over the wire; is each completion entry expensive - are we sending an unexpected amount of data?

**Comment by timsneath** [comment]
We're seeing some additional evidence of this from Twitter, with a number of reports / corroborations in this thread: https://twitter.com/MatthewRideout/status/1439972286883315712

**Comment by atreeon** [comment]
> Thanks @maheshmnj . A +1 from me here. I was using Flutter 2.2.1 which was a little bit slow but 2.5 is making intellisense and code completion unusable (its easier to type in the results). I do have a large project but it was kind of ok previously.

Just to say that my problem was mostly remedied after I allocated more memory to IntelliJ ```InteliJ IDEA CE.app.vmoptions```, I was previously using the default options which might not be recommended.  Possibly my problem is different to the OP's problem.  Could 2.5 use more memory?  Good news is everything is ok enough for me, still a tiny lag but one that doesn't bother me.

**Comment by jwren** [comment]
I have been looking into this issue and believe that I have a proposal to fix it.  Working with @jacob314 to figure out a path forward to staff the work and get the SDK patched.

**Comment by KlausJokisuo** [comment]
Great to see that this is getting attention. I think the sluggishness has been an ongoing issue for a while now, even before this release. VSCode seems to be faster than IntelliJ regarding code completion and code analysis, at least on previous versions.

**Comment by Lootwig** [comment]
> > Thanks @maheshmnj . A +1 from me here. I was using Flutter 2.2.1 which was a little bit slow but 2.5 is making intellisense and code completion unusable (its easier to type in the results). I do have a large project but it was kind of ok previously.
> 
> Just to say that my problem was mostly remedied after I allocated more memory to IntelliJ `InteliJ IDEA CE.app.vmoptions`, I was previously using the default options which might not be recommended. Possibly my problem is different to the OP's problem. Could 2.5 use more memory? Good news is everything is ok enough for me, still a tiny lag but one that doesn't bother me.

@atreeon how much? I've got 8GB allocated, of which only 1 is used, and it's just as slow as shown in the videos above

**Comment by atreeon** [comment]
@Lootwig I've got 4GB allocated, if you've got 8GB specified it won't be that! (I've seen it go up to about 1.8gb and mine was previously around 800mb or seomthing like that).  Mine is just as slow as in the video but a lot better than it was previously.  Interestingly it is slow in a Flutter project but ok in Dart.

**Comment by scheglov** [comment]
Some experiments.
All times are in milliseconds.

1. Initial state, no filtering.
`1632428517931 [Perf: <request>: 339, getResolvedUnit: 0, computeSuggestions: 85, DartCompletionManager: 85, build DartCompletionRequest: 0, ArgListContributor: 0, CombinatorContributor: 0, ExtensionMemberContributor: 0, FieldFormalContributor: 0, ImportedReferenceContributor: 81, KeywordContributor: 0, LabelContributor: 0, LibraryMemberContributor: 0, LibraryPrefixContributor: 0, LocalLibraryContributor: 0, LocalReferenceContributor: 0, NamedConstructorContributor: 0, OverrideContributor: 0, RedirectingContributor: 0, StaticMemberContributor: 0, TypeMemberContributor: 0, UriContributor: 0, VariableNameContributor: 0, filter: 3 (count: 3250, matchCount: 3250), send notification: 252, ]`

2. Filter using an already typed prefix, in this case `M` (matches `Material` widgets). This makes it **4x** faster. All of it because we send 20x fewer suggestions - `146` our of `3250`.
`1632428638475 [Perf: <request>: 79, getResolvedUnit: 0, computeSuggestions: 69, DartCompletionManager: 69, build DartCompletionRequest: 0, ArgListContributor: 0, CombinatorContributor: 0, ExtensionMemberContributor: 0, FieldFormalContributor: 0, ImportedReferenceContributor: 66, KeywordContributor: 0, LabelContributor: 0, LibraryMemberContributor: 0, LibraryPrefixContributor: 0, LocalLibraryContributor: 0, LocalReferenceContributor: 0, NamedConstructorContributor: 0, OverrideContributor: 0, RedirectingContributor: 0, StaticMemberContributor: 0, TypeMemberContributor: 0, UriContributor: 0, VariableNameContributor: 0, filter: 1 (count: 3250, matchCount: 146), send notification: 7, ]`

3. We can cache `CompletionSuggestion` instances for `Element` using `Expando` in `SuggestionBuilder`. This makes it **another 4x** faster. All of it because `ImportedReferenceContributor` is much faster.
`1632429007472 [Perf: <request>: 20, getResolvedUnit: 1, computeSuggestions: 10, DartCompletionManager: 10, build DartCompletionRequest: 0, ArgListContributor: 0, CombinatorContributor: 0, ExtensionMemberContributor: 0, FieldFormalContributor: 0, ImportedReferenceContributor: 7, KeywordContributor: 0, LabelContributor: 0, LibraryMemberContributor: 0, LibraryPrefixContributor: 0, LocalLibraryContributor: 0, LocalReferenceContributor: 0, NamedConstructorContributor: 0, OverrideContributor: 0, RedirectingContributor: 0, StaticMemberContributor: 0, TypeMemberContributor: 0, UriContributor: 0, VariableNameContributor: 0, filter: 2 (count: 3250, matchCount: 146), send notification: 8, ]`

@alexander-doroshko @bwilkerson @DanTup

**Comment by scheglov** [comment]
Note, that this is not what users could get right now, but just what could be achieved. All completions above were for already resolved file, just typing `Ctrl+Space`. In most cases however the user types a character, and so two things happen:
1. All the library elements are discarded and reloaded from summaries, this prevents returning cached `CompletionSuggestion`s in `SuggestionBuilder` - we have new instances of all elements, so the `Expando` is empty for them. See `ImportedReferenceContributor: 194`.
2. We spend time to resolve the unit where completion happens. See `getResolvedUnit: 112` below. I think the number is high because we spend time to build namespaces of large imported libraries.

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

void f() {^
  print(42);
}
```

As a result, even with filtering performance is not great.
`1632430192285 	[Perf: <request>: 337, getResolvedUnit: 112, computeSuggestions: 197, DartCompletionManager: 197, build DartCompletionRequest: 0, ArgListContributor: 0, CombinatorContributor: 0, ExtensionMemberContributor: 0, FieldFormalContributor: 0, ImportedReferenceContributor: 194, KeywordContributor: 0, LabelContributor: 0, LibraryMemberContributor: 0, LibraryPrefixContributor: 0, LocalLibraryContributor: 0, LocalReferenceContributor: 0, NamedConstructorContributor: 0, OverrideContributor: 0, RedirectingContributor: 0, StaticMemberContributor: 0, TypeMemberContributor: 0, UriContributor: 0, VariableNameContributor: 0, filter: 1 (count: 3246, matchCount: 146), send notification: 26, ]`

It would have been even worse (on about `200 ms`), as what we have today.

Fortunately it could be improved so that completion in the trivial code like above is about `20 ms`. We need to improve the analyzer to keep these `package:flutter` libraries. But it will take a few days to carefully implement it.

**Comment by scheglov** [comment]
Same as https://github.com/flutter/flutter-intellij/issues/5761#issuecomment-926163237, but if keeping unaffected library elements: `337 ms` turn into `24 ms`.
`[Perf: <request>: 24, getResolvedUnit: 7, computeSuggestions: 10, DartCompletionManager: 10, build DartCompletionRequest: 0, ArgListContributor: 0, CombinatorContributor: 0, ExtensionMemberContributor: 0, FieldFormalContributor: 0, ImportedReferenceContributor: 6, KeywordContributor: 0, LabelContributor: 0, LibraryMemberContributor: 0, LibraryPrefixContributor: 0, LocalLibraryContributor: 0, LocalReferenceContributor: 0, NamedConstructorContributor: 0, OverrideContributor: 0, RedirectingContributor: 0, StaticMemberContributor: 0, TypeMemberContributor: 0, UriContributor: 0, VariableNameContributor: 0, filter: 2 (count: 3246, matchCount: 146), send notification: 7, ]`

**Comment by Angeloem** [comment]
I thought this was me only....

I found out that invalidating caches and restarting sometimes fixed the problem for such a session! This would happen 2 out of roughly 6 times..

**Comment by scheglov** [comment]
Yes, we can close this issue.
The acute issue has been fixed.
We have more work planned on code completion in Q4.

**Comment by KlausJokisuo** [comment]
Ideas when Dart 2.14.3 will be included with Flutter Stable?

**Comment by xshiwei** [comment]
Flutter plans to update the DART version when

**Comment by mit-mit** [comment]
This is now available in Flutter stable, version 2.5.2.

**Comment by SametSahin10** [comment]
> This is now available in Flutter stable, version 2.5.2.

The [Dart](https://plugins.jetbrains.com/plugin/6351-dart) plugin needs to be updated in order to get this fix. Is that right?

**Comment by DanTup** [comment]
@SametSahin10 the change is in the SDK. Upgrading Flutter to v2.5.2 (by running `flutter upgrade`) and restarting your IDE should be enough.

**Comment by KlausJokisuo** [comment]
The problem still exists at least on IntelliJ platform. I've raised another issue regarding this.

https://github.com/flutter/flutter-intellij/issues/5825

**Comment by ldsouza93** [comment]
i'm losing hope, i have a ryzen 7 4800h and 16gb ram, ssd, thermals all fine and android studio is very slow

**Comment by mit-mit** [comment]
@ldsouza93 sorry to hear that you are having issues. This is a closed, year old issue. Can you kindly file a new issue, and detail what versions you are using, and what you are experiencing?

**Comment by jwren** [comment]
@ldsouza93 Yes, sorry to hear you are experiencing a slow developer experience.  Yes, do create a new issue with more information.  With your project in VS Code, with the same analysis server, do you experience the same slowness?
