### ISSUE TITLE
Debugging iOS over Wi-Fi

### ISSUE THREAD

**Issue by fatadel** [flutter/flutter-intellij#5790]
It is possible to debug iOS devices over Wi-Fi in Xcode but not in IntelliJ IDEA (at least I cannot find it). Isn't that supported, and if so, is it planned to be implemented?

**Comment by stevemessick** [comment]
Xcode is completely separate from IntelliJ. If wifi support was added to IntelliJ then perhaps it would be possible. I doubt it will be, since JetBrains has their own competitor to Xcode (AppCode). AppCode does not recognize Flutter projects, so it can't be used.

Alternative, it may be possible to have the Flutter SDK support a wireless connection, but that would depend on the Android SDK. If the Android SDK supports wifi then you could file a feature request with [flutter/flutter](https://github.com/flutter/flutter/issues).
