### ISSUE TITLE
AVD Manager lack in the Main Menu of Android Studio Bumblebee 2021.1.1 to start a Virtual Device

### ISSUE THREAD

**Issue by SEAFromJahu** [flutter/flutter-intellij#5934]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by SEAFromJahu** [comment]
Android Studio Bumblebee 2021.1.1
In the main menu, the icon that should allow access to the creation and/or start of Virtual Devices is not operational when we move the mouse pointer above it. "AVD Manager" no longer appears "AVD Manager" now only "Device Manager" appears and when clicking on it we have no reaction none ( is dead) in current Android Studio IDE...

**Comment by stevemessick** [comment]
This is due to #5464. To work around the problem, see this [comment](https://github.com/flutter/flutter-intellij/issues/5464#issuecomment-836857485).

The next plugin release will fix the problem for new projects. For existing projects, you can use the work-around, or recreate the project. Fixing #5932 will solve the problem for existing projects.
