### ISSUE TITLE
IntelliJ plugin launches from pub

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter-intellij#6004]
Connecting to a new device using the websocket URL shows this warning:

![Screen Shot 2022-03-01 at 1 10 32 PM](https://user-images.githubusercontent.com/1145719/156249447-ec5948ad-dabc-4744-8360-6a116c1c0427.png)

**Comment by helin24** [comment]
We changed back to pub here: https://github.com/flutter/flutter-intellij/pull/5851

Maybe because starting the flutter tools daemon has some risk of failing and we don't want to wait for it? I think we'll either start the daemon later or accept using divergent methods for starting devtools for internal and external users.
