### ISSUE TITLE
IDE Crashes when opening existing flutter project

### ISSUE THREAD

**Issue by suniljdh** [flutter/flutter-intellij#6014]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.
[bug-report_1.md](https://github.com/flutter/flutter-intellij/files/8183190/bug-report_1.md)

**Comment by stevemessick** [comment]
No actionable info here.

**Comment by kelton-glitch** [comment]
I recently switched OS (Windows to Linux) due to some OS glitches and I set up the flutter environment in the new system and I've not been able to run any flutter project since

- The emulator takes extremely long to boot up in Vscode so I switched to Android studio

- In Android Studio, the emulator starts up just fine but crashes everytime I run the project and any other previously working flutter project. It does not even build. It crashes and the IDE closes immediately

I tried doing a flutter clean and it still hasn't helped

**Comment by kelton-glitch** [comment]
I recently switched OS (Windows to Linux) due to some OS errors. I setup my environment for flutter using the latest updates in the IDE and SDK's needed.

- The emulator(Pixel 4 using Android 33) takes a very long time to launch or does not launch to completion when I'm in VScode

- So I switched to Android studio and it launches well there, but I have not been able to run any flutter project since then.
- The IDE closes crashes and closes after I initiate "flutter run"
- I tried doing flutter clean on the projects, but it didn't change anything 

I don't seem to understand what the problem is
