### ISSUE TITLE
problem with Icons

### ISSUE THREAD

**Issue by AmirAbdr** [flutter/flutter-intellij#6191]
I have a problem dealing with flutter icons using font_awesome_flutter dependency.
Some of the icons doesn't show up while using the android studio , or even after deploying the project on my emulator. 
note : this problem is only in my computer ,  when I use another device , it works properly.
![icons](https://user-images.githubusercontent.com/96000319/170056164-d427d147-318a-4482-a189-c357b9a041fd.PNG)
![icons2](https://user-images.githubusercontent.com/96000319/170056169-c2c4d6e0-b82b-4ebf-9bec-c064ab73f9f6.PNG)

**Comment by stevemessick** [comment]
Please add the output of `Tools > Flutter > Flutter Doctor` here.

Which emulator did you use? I could not reproduce the problem with a Pixel 5 emulator. The percent icon appeared in my sample project. BTW, `Icons.percent` is a material icon, not the pub package you mentioned.

I suspect the problem with icon previews disappearing in the editor is due to the font file format used in Flutter 3.0 for material icons. I'm looking into that. Some appear, others do not, which suggests to me that Java 11 isn't able to process all the icons.

**Comment by AmirAbdr** [comment]
this is the flutter doctor output:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 2.10.0, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.65.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.


====>

this the emulator I am running on 

![image](https://user-images.githubusercontent.com/96000319/170210749-1a1afed6-e202-4dbf-8e65-e24be03532be.png)

**Comment by stevemessick** [comment]
Please add the output of `Tools > Flutter > Flutter Doctor` here (or run `flutter doctor -v`).

Can you create another emulator with a more recent Android API version and see if the icon shows up when running with it?
