### ISSUE TITLE
Project view shows many files that first-time users may be confused about

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#630]
First-time users will likely try to make sense of each and every entry shown in the Project view. Thus it's important this only contains things they actually need to worry about.

I think we should be hiding the following:

1. `.idea` dir: IDE settings that are typically edited using the IJ UI itself
1. `.iml` file: Same as above
1. `.packages` file: Generated pub artefact
1. `pubspec.lock` file: Generated pub artefact

Additionally, the Dart plugin will automatically hide these:
1. `.pub` dir: The local pub cache, not for editing
1. `build` dir: build outputs, not a source artefact

**Comment by alexander-doroshko** [comment]
My $0.02.
I'd like not to decide for users whether they want to see all files as they exist in the file system or not.

For example: for a long time we used to hide excluded folders from the Project View. But so many users were unhappy with it, so some day we introduced an option to show excluded files (gear menu in the Project View tool window header). And a bit later we even made it the default.

You may document this gear option: disabling it will hide `.pub` and `build`. Though I'm sure a lot of users will finally prefer to keep `build` folder contents visible.

As for the `*.iml` file: it doesn't have to be in the project root. Your flutter app generator may place it inside `.idea` folder with the coresponding path in `.idea/modules.xml`.

Finally. Yes, it is possible to implement some hacky magic so that some specific files and folders are not visible in the Project View. But I'm strongly against this magic. I think it would introduce much more confusion than seeing file structure as is.

**Comment by mit-mit** [comment]
I want the project view to hide these exactly in the case you describe: When 'Show excluded files' is set to No. I am totally fine with them being shows when `Show excluded files` is Yes.

To get that, don't we need to mark these with `excludeFolder` in the `.iml` file? Or is what is shown/hidden depending on that toggle controlled elsewhere?

**Comment by alexander-doroshko** [comment]
Unfortunately individual files exclusion is not supported.

Folder `build` and `.pub` should be excluded automatically (Dart plugin should do the trick even if auto-generated project template doesn't).

`*.iml` may be placed inside `.idea` on project creation

As for `.packages` and `pubspec.lock` - I'm afraid no way to hide them.

**Comment by mit-mit** [comment]
Thanks for the tip on `build` and `.pub`, that seems to work!

**Comment by pq** [comment]
Thanks for the input @alexander-doroshko !

> *.iml may be placed inside .idea on project creation

Interestingly we just moved away from this format for the examples as I believe it's not what project creation does.  Or is that configurable?

FWIW the relevant IDEA feature request is here: https://youtrack.jetbrains.com/issue/IDEA-129625

**Comment by mit-mit** [comment]
We also shouldn't have two `.yaml` files -- that will be resolved by https://github.com/flutter/flutter-intellij/issues/630

**Comment by alexander-doroshko** [comment]
> Interestingly we just moved away from this format for the examples as I believe it's not what project creation does

Indeed, by default all IntelliJ IDEA's project/module wizards suggest to place IML in the module content root. But at wizard step it is possible to change IML file location manually.

Small IDEs have single-module projects and place IML into .idea folder.
I personally like IMLs in .idea folder, but I speak for myself only. I do not know why default place for IML in  IntelliJ IDEA is content root, probably historical reasons only.

**Comment by pq** [comment]
Thanks @alexander-doroshko!

@mit-mit and @devoncarew and I had some back and forth about where to put IML files in our samples and I'm actually OK with whatever --- though making them hidable is a perk of putting them in `.idea/`...

> Small IDEs have single-module projects and place IML into .idea folder.

Will small IDEs work with IML files at the top-level?

**Comment by alexander-doroshko** [comment]
> Will small IDEs work with IML files at the top-level?

Yes, the engine is the same.

**Comment by mit-mit** [comment]
If the behavior is all the same, I think I prefer them inside .idea

**Comment by pq** [comment]
Works for me.  Any objections @devoncarew?

**Comment by devoncarew** [comment]
No, sgtm

**Comment by pq** [comment]
Great.  Tracking issue: https://github.com/flutter/flutter-intellij/issues/632.

**Comment by mit-mit** [comment]
> Folder `build` and `.pub` should be excluded automatically (Dart plugin should do the trick even if auto-generated project template doesn't).

Hi @alexander-doroshko, I tried to remove these from the `.iml` file, and that does indeed work: On project open, the are still hidden when 'show excluded' is no. However, I noticed that after running a `pub get` they get added to the `.iml` file resulting in that being dirty. Is that expected? I thought the dart-plugin would just filter them out without that in `.iml`.

**Comment by alexander-doroshko** [comment]
The trick is that on project open and also on any Pub action started from the IDE Dart plugin auto-excludes these folders that results in the corresponding lines in the IML. You probably didn't see dirty IML right after project open because it was not saved at that moment, but in memory IML was already updated with these lines.

So you shouldn't remove these from the IML, they are there exactly for this purpose.
