### ISSUE TITLE
Debugger `View` cuts the information short.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter-intellij#6312]
The debugger lets us inspect object values. One way is navigating through the object's properties, one by one. But that can be difficult. Another way is just pressing the `View` button to get the object's toString() output.

However, the debugger cuts this information short, probably to save memory?

For example, this is the `View` output for a variable called `someObjectWithInformati`:

```
someObjectWithInformati{cliente: null, empresa: null, parceira: null, dayHourMin: 2022-09-18T00:00:00.000Z, agd: null, colabs: P
```

That's only 128 chars. If, however, I add a watcher for `someObjectWithInformati.toString()` then I get the complete output:

```
someObjectWithInformati{cliente: null, empresa: null, parceira: null, dayHourMin: 2022-09-18T00:00:00.000Z, 
agd: null, colabs: ParticipantesIds {|colabsPorEmpresa: { }  IMapOfSetsConst<EmpresaId, PessoaId>|pessoasAvulsas: { }
ISetConst<PessoaId>|confirmacoes: { }  IMapConst<PessoaId, Confirmacao>|}}
```

The whole point of the debugger is making it easy for us to debug. Cutting the information short to save a few bytes of memory in 2022 makes little sense. It forces me to create whatchers adding `toString()` everywhere, or else inspect through the properties where a single glance to the `View` output would suffice.

Please let this information contain the complete `toString()` output. At least the Watch tab should contain complete outputs, but ideally everywhere.

If you absolutely must have a limit there, please make if 100kb instead of only 128 chars.

**Comment by stevemessick** [comment]
I can't find a `View` button. I checked both Android Studio and IntelliJ. (Also checked VS Code.) Can you give me a screen shot that shows it? Could it possibly be added by another plugin? I even checked the Keymap for a command named `View` but couldn't find one.

**Comment by marcglasberg** [comment]
@stevemessick The View button is visible when you add a watch, and it's `toString()` result doesn't fit the window. For example, this code:

```
var names = ['Lucy', 'James', 'Cesar', 'Anna', 'Drake'];
var namesStr = names.join('\n');
```

![ViewButton](https://user-images.githubusercontent.com/13332110/192118258-c87b2826-21ad-4811-af1d-e5556628f6bd.png)

**Comment by marcglasberg** [comment]
The View button is also shown for the variables in the local parameter window (the one that shows all the values in scope). But there you have more space, so you need larger `toString()` results to show the view button.

**Comment by stevemessick** [comment]
I cannot reproduce this problem. I added a long String variable to some existing code. `lfen` is just 12 copies of `_fen` concatenated together with a space between them.
```
_fen = 'rnbqkb1r/pppp1ppp/7n/4p3/8/2PPP3/PP3PPP/RNBQKBNR b KQkq - 0 3'
```
Yes, the `View` button shows up after the variable and value in the `Variables` pane.

<img width="160" alt="Screen Shot 2022-09-26 at 10 53 11 AM" src="https://user-images.githubusercontent.com/8518285/192346949-2ce798ab-e23b-4c4d-9d5c-f17a846c043a.png">

When I click `View` I get the full value.

<img width="663" alt="Screen Shot 2022-09-26 at 10 52 45 AM" src="https://user-images.githubusercontent.com/8518285/192347036-74731200-6f67-44be-9fc3-8f27beb6ff94.png">

For reference, here's the Java code that computes that value.

<img width="999" alt="Screen Shot 2022-09-26 at 10 53 32 AM" src="https://user-images.githubusercontent.com/8518285/192347161-1472e1f2-6502-45cf-b27e-8aa55912fba6.png">

The code in that screen shot hasn't changed since it was written years ago so I don't think this is due to an out-of-date plugin.

Interestingly, the initial value is indeed truncated to 128 chars. That's the `presentableValue` variable. But the code on line 205 changes it to use the full string length. I stepped through with the debugger and can confirm that line 205 does get executed. Apparently, the condition on line 204 evaluates to `false` for you but I don't know why that would happen. That test extracts a value from the JSON sent from the VM.

These screen shots were a debugging session using a variable in the `Variables` pane. But the same thing happens when I use the `Watches` pane. Both run through line 205. Is there anything else about your setup that might be unique? I'm pretty sure I have not customized anything (but could have forgotten something). I'm using Flutter 3.3.2.

@bkonyi Do you have any insights about what might be happening here?

**Comment by bkonyi** [comment]
@stevemessick I'll be completely honest with you, I don't really know much about the Java implementation in `package:vm_service` :(

Maybe @devoncarew or @jacob314 would know more? One of them wrote the generator for the Java sources at some point.

**Comment by devoncarew** [comment]
@stevemessick - I think you're right in that the issue is likely one of presenting a truncated string value. Perhaps there's another code path where we're not checking for and querying for the full string?

**Comment by stevemessick** [comment]
@devoncarew I think that's it. I realized as I was out for a walk that I was using a String, not something that had to have `toString()` applied. I'll look again.

@bkonyi That's for the redirect.

**Comment by stevemessick** [comment]
I was able to repro the problem. A PR to fix it is out for review. I'm planning a point release in the next few days so you should get the fix this week, @marcglasberg.

**Comment by marcglasberg** [comment]
Amazing, Steve! Thank you so much.
