### ISSUE TITLE
Remove "Format code on save" settings

### ISSUE THREAD

**Issue by stevemessick** [flutter/flutter-intellij#6581]
IntelliJ has this option implemented to use `dartfmt`. We may also be able to remove the "Organize imports on save" setting, but need to confirm the behavior is the same.

**Comment by alexander-doroshko** [comment]
FYI. By default, all Actions on Save are turned off but the plugin can change this. See `com.intellij.codeInsight.actions.onSave.FormatOnSaveOptionsBase.DefaultsProvider` extension point. If you want, you can make Dart files be formatted on save by default.

**Comment by stevemessick** [comment]
That's good to know, thanks. Our default is `false` and I don't think we've considered changing it, but we could.

cc @jacob314

**Comment by alexander-doroshko** [comment]
Also FYI. As people might be looking the 'Format Dart on save' option on the Flutter page, instead of removing the check box completely, you can replace it with the link to the `Actions on Save` page. See `com.intellij.ide.actionsOnSave.ActionsOnSaveConfigurable#createGoToActionsOnSavePageLink`

**Comment by jacob314** [comment]
@DanTup am I correct that the default in the VSCode Dart plugin is to format on save?

**Comment by DanTup** [comment]
@jacob314 it's not the _default_, but the first time you run the extension there's a prompt asking if you'd like to use the _recommended_ settings [which does enable it](https://dartcode.org/docs/recommended-settings/).

I try to avoid setting too many things by default, because VS Code makes language-specific defaults very difficult to see/change and that's caused some confusion. Recommended settings just get written into your user settings, so you can easily see/modify them.

For users opted-in to analytics, ~40% have format-on-save enabled.

**Comment by stevemessick** [comment]
Closing in favor of #6592
