### ISSUE TITLE
Really don't like the web-based Embedded inspector, will the legacy inspector come back?

### ISSUE THREAD

**Issue by debuggerx01** [flutter/flutter-intellij#6749]
## Steps to Reproduce

The JxBwowser based inspector is slow to use and takes up a lot of memory.

#6728

**Comment by debuggerx01** [comment]
And there are many bugs, the widget tree often cannot be displayed:

![image](https://github.com/flutter/flutter-intellij/assets/19624835/dac42c08-fb61-4008-964b-3e5283349659)

**Comment by stevemessick** [comment]
Since no one on the DevTools team has seen the problem in your screen shot, perhaps you can give us some information on how to reproduce it? Have you ever seen this problem while using DevTools in the browser? What did you do to get into that state? It looks like you're using the old UI; is that right?

What version of DevTools do you have? Attaching the output from `flutter doctor -v` will help a lot.

For now, you can go back to the stable (or beta) version of Android Studio. The linked PR is only present in the canary build of the Flutter plugin. (Mea culpa, it was not supposed to be in any build prior to June 1, but I wanted to get a canary build out quickly.)

cc @kenzieschmoll @helin24

**Comment by helin24** [comment]
It might be time to set up the JCEF browser and see if this helps users who are having trouble with the JxBrowser implementation.

@debuggerx01 do you have this issue when you open DevTools in a normal browser tab, or is it only in the embedded browser?

**Comment by debuggerx01** [comment]
I think the problem I'm having is this: https://github.com/flutter/devtools/issues/5773

But what I actually want to say is that I hope not to remove the legacy inspector, it works fine for me, I prefer to use it instead of DevTools
@helin24 @stevemessick

**Comment by helin24** [comment]
@debuggerx01 I'm sorry to say there are some APIs used by the legacy inspector that are no longer being supported, and it doesn't make sense for us to continue supporting this option along with the embedded inspector. If you are restricted to using an older version of flutter, I think the best option would be to continue using an older version of the Flutter IntelliJ plugin, since these two things will remain compatible.
