### ISSUE TITLE
Consider not overriding OpenProjectProcessor.isStrongProjectInfoHolder().

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#684]
Follow-up from: https://github.com/flutter/flutter-intellij/pull/682#issuecomment-276075967.

**Comment by pq** [comment]
@alexander-doroshko : if I remove this override, `FlutterProjectOpenProcessor` no longer has a chance to intervene if the project has an IML or project metadata.  Happy to explore other approaches if you have ideas.

**Comment by alexander-doroshko** [comment]
The original idea of ProjectOpenProcessor is to help to **create** a project when the project has already been set up using some other IDE or build tool, but has not yet been set up in IntelliJ IDEA. Clients of ProjectOpenProcessor are: 
- `EclipseProjectOpenProcessor` - helps with initial `.idea` project setup if there is Eclipse's `.project` file available
- `GradleProjectOpenProcessor` - obviously tries to translate gradle project model to IntelliJ's
- `MavenProjectOpenProcessor` - the same for `pom.xml`

All above work once and do not do anything when IntelliJ's project is opened next time. Instead, the corresponding plugin may say like "pom.xml has changed, would you like to reimport the maven project?", etc.

`isStrongProjectInfoHolder()` was added to the API for AppCode because in that world XCode project files are more important than IntelliJ's.

So yes, standard use case is not to modify already configured project.
If your OpenProjectProcessor rewrites project model on each project opening, you give user no chance to configure it in a different way. Well, may be that's what you want. I can't say for sure which way is 'correct' for you. The main thing is not to do anything with non-flutter users.

**Comment by devoncarew** [comment]
assumed stale -
