### ISSUE TITLE
DevTools pages do not load in the correct theme

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter-intellij#7319]
![Screenshot 2024-04-04 at 8 06 55 AM](https://github.com/flutter/flutter-intellij/assets/43759233/ee0ae3e9-f0ba-48b8-9f5b-ce8beeb48ef6)

![Screenshot 2024-04-04 at 8 11 55 AM](https://github.com/flutter/flutter-intellij/assets/43759233/06b62fc8-0b71-42a1-af07-2d50739a39d6)

@helin24 are we properly passing the ide theme query parameters? 
CC @DanTup I thought you fixed a similar issue in the VS Code extension but I couldn't find a link. Can you share what the URL looks like on the VS Code side?

**Comment by DanTup** [comment]
> CC @DanTup I thought you fixed a similar issue in the VS Code extension but I couldn't find a link. Can you share what the URL looks like on the VS Code side?

I'm not sure about fixing this specifically (we do have a few outstanding theming issues), but the way we pass theming info is on the querystring like this:

https://github.com/Dart-Code/Dart-Code/blob/3d2201c1d39cbeadf2da781819284264ff8d6b17/src/extension/flutter/sidebar.ts#L63-L73

We add querystring params for `embed=true`, `theme=(dark|light)` and also `backgroundColor` and `foregroundColor` (which DevTools uses if they are close enough to dark/light values, to try and make it fit with custom themes better) and `fontSize`.

**Comment by ImadBouirmane** [comment]
Okay but @DanTup is also the same on Android studio https://github.com/flutter/devtools/issues/7506

**Comment by helin24** [comment]
Hmmm.. is `backgroundColor` the right way to pass in theming info?

This is an example URL that we are generating: `http://127.0.0.1:56296/deep-links?ide=Android-Studio&backgroundColor=f7f8fa&embed=true&fontSize=13.0&ideFeature=toolWindow`

**Comment by DanTup** [comment]
@helin24 there is some code to ensure the custom background colour is close enough to the default background so that the contrast of other colours in DevTools isn't too bad:

https://github.com/flutter/devtools/blob/e2a7208bb8eed852b1f9dedabf423f187e947a7d/packages/devtools_app_shared/lib/src/ui/theme/theme.dart#L42

This means you probably need to ensure `theme=light` / `theme=dark` is passed correctly too.

If I try:

http://127.0.0.1:9101/deep-links?backgroundColor=f7f8fa&embed=true

I see a dark background because the theme is Dark and the background is considered too different. But if I add `&theme=light`, then I see the correct color background (I also tested with `ffeeee` to confirm it turned red, to ensure I was seeing the custom colour and not just the default light theme bg).
