### ISSUE TITLE
Flutter IntelliJ IDEA 2024.1 -- `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by chardinson** [flutter/flutter-intellij#7330]
## What happened

I don't know

## Version information

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 78.5.1` • Dart plugin `241.14768`

Error getting Flutter sdk information.

## Exception

null

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.flutter.actions.ExtractWidgetAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.flutter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by jacob314** [comment]
Use of a deprecated API that needs to be fixed soon so that important ExtractWidgetAction continues to work.

**Comment by helin24** [comment]
We're not using the deprecated code directly in ourplugin. I see this [issue in IDEA](https://youtrack.jetbrains.com/issue/IDEA-344189/com.intellij.diagnostic.PluginException-ActionUpdateThread.OLDEDT-is-deprecated-and-going-to-be-removed-soon-after-restoring) that should be fixed now, but perhaps will remain for a while in 2024.1.

It seems like this is an issue within an IJ class somewhere in the inheritance chain of `DefaultActionGroup`, and should be fixed there rather than us needing to supply a non-deprecated thread type everywhere that we extend the class.

**Comment by j-fbriere** [comment]
Same problem for me.

IntelliJ IDEA `2024.1` • Flutter plugin `io.flutter 78.5.1` • Dart plugin `241.15845`

Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (10 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

**Comment by jwren** [comment]
This isn't just in the extract widget action, see https://github.com/flutter/flutter-intellij/issues/7341.  `io.flutter.actions.RunProfileFlutterApp`
