### ISSUE TITLE
IntelliJ Platform Gradle Plugin (2.x) migration / Flutter plugin IDE (IntelliJ IDEA 2024.3 EAP)

### ISSUE THREAD

**Issue by yasergh** [flutter/flutter-intellij#7670]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by jwren** [comment]
I started to look at this, but versions of the currently required Kotlin plugin aren't being pulled down.

```
{
      "channel": "stable",
      "comments": "IntelliJ 2024.3",
      "name": "2024.3",
      "version": "2024.3",
      "isUnitTestTarget": "false",
      "ideaProduct": "idea",
      "ideaVersion": "243-EAP-SNAPSHOT",
      "baseVersion": "243.16718.32",
      "androidPluginVersion": "243.16718.32",
      "dartPluginVersion": "243.16718.30",
      "sinceBuild": "243.16718.30",
      "untilBuild": "243.*"
    }
```

```Cannot find builtin plugin 'Kotlin' for IDE: /Users/jwren/.gradle/caches/modules-2/files-2.1/...```

**Comment by jwren** [comment]
In order to continue to roll to new platform versions, starting with `2024.3`, a migration to IntelliJ Platform Gradle Plugin (2.x) migration is required:
- https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-migration.html
- https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html
- https://github.com/JetBrains/intellij-platform-gradle-plugin/releases
- https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html

**Comment by jwren** [comment]
Currently blocked by not being able to add dependencies into the Flutter IJ plugin, see issue opened here on the Gradle IJ project team: https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1810.

**Comment by jwren** [comment]
Closing out as finished, however some cleanup activities will continue in this space.

**Comment by ThomasDevApps** [comment]
Hi @jwren, due to its great usefulness, do you have any idea when the Flutter coverage support will reappear ?
