### ISSUE TITLE
Fix breakpoints in same package when running on mac bazel with READONLY

### ISSUE THREAD

**Issue by gavindoughtie** [flutter/flutter-intellij#784]
Set a breakpoint in IntelliJ (Community edition on OSX, with Flutter and Dart plugins). Attach debugger over the port specified when running app via iOS simulator from command line.

Expected:
IntelliJ stops at breakpoint.
Actual:
IntelliJ console logs from the running app, but breakpoint does not trigger.

**Comment by eseidelGoogle** [comment]
To confirm: is this using the `flutter run` based workflow or the bazel based commandline workflow?

**Comment by devoncarew** [comment]
@gavindoughtie, this is using the remote debug configuration? @skybrian has done a bunch of work to get the bazel workflow working on a mac (not all of it may be in the current stable release).

**Comment by skybrian** [comment]
@gavindoughtie, could you file an internal bug with the Google-specific details?

**Comment by gavindoughtie** [comment]
Filed bug to devoncarew with the internal details (bazel build)

**Comment by skybrian** [comment]
Okay, reassigned to me.

**Comment by skybrian** [comment]
I haven't done much actual work on this lately, but did learn some things while testing that might be helpful:

It looks like we are okay for most Dart packages (when they use package: imports). In that case, we use the analysis server to resolve source positions, and it generally does the right thing for Bazel.

Things are messier for .dart files in the same package as lib/main.dart. It mostly works provided that you set the "working directory" field to the directory containing "lib/main.dart", but doesn't handle generated files. (It looks like Gavin's project recently did a refactoring so that generated code is in a different package, so they might not be seeing this anymore.)

If you set working directory incorrectly, breakpoints will work until you do a hot reload, then stop working.

I've been thinking we either need to do more error-checking on working directory, or perhaps replace the working directory field with something less ambiguous. Asking the user to choose the location of main.dart seems clearer, and we can automatically calculate the application directory and Bazel workspace directory based on that.

**Comment by skybrian** [comment]
Seems low priority these days, since most people don't use a setup with a READONLY directory.

**Comment by devoncarew** [comment]
assumed stale -
