### ISSUE TITLE
Make it clearer to developers when and how to 'hot reload' vs 'hot restart' vs 're-run'

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter-intellij#803]
I just watched a [developer presentation](https://adwd.github.io/dart-flutter-slide/) on using Flutter. 

There is an animated gif where the developer uses `hot restart` to change a String from 'Flutter' to 'Dart' in their build method. 

This is a missed opportunity to use hot reload and it appears the developer isn't even aware of the feature.

We should encourage developers to try hot reloading.

@lukechurch @mit-mit @sethladd

**Comment by mit-mit** [comment]
AFAIK we have not seen this in the UX studies.

One possible change is suggested in https://github.com/flutter/flutter-intellij/issues/810, I speculate that might be enough for now?

**Comment by johnmccutchan** [comment]
@mit-mit did you watch the video in the link I sent?

**Comment by lukechurch** [comment]
I think we haven't seen this in the studies more by luck and the artefact that our participants tend to read left -> right than because our participants really understanding the difference.

I agree with @johnmccutchan that we could to do better here. I would really like us to get to a point where we could make a reasonable guess that hot reload would have 'done what the user wanted', this video is a clear example of that. 

How difficult would it be to get analytics data that the changes could have been hot reloaded, but we instead were instructed to do a restart? Even if the metric has some false negatives it would be nice to get a sense of whether this is a major problem or not.

Given that this is such a key UX, I would support adding a feedback mechanism that said if the user had done say 5 repeated restarts in a row with relatively little time between them we print a url to the console asking them to tell us if they knew of hot reload, and if so why it is that reload isn't working for them.

**Comment by mit-mit** [comment]
I agree we need to do more, see the analytics numbers I quoted in #8717.

But I worry about prompting in the case of false positives. What if the developer is testing their initialization logic and that is why they are restarting?

We could consider something like what Android Studio just rolled out:

>... we have made some significant changes to Instant Run in Android Studio 2.3 ... The Run action will now always cause an application restart to reflect changes in your code that may require a restart, and the new Apply Changes action will attempt to swap the code while your app keeps running

![](https://1.bp.blogspot.com/-tiW6x503J_c/WLhSflDxIHI/AAAAAAAAD8A/EUwQJ8GmeCQzTT9OBG-KR8x9qumvVyhcwCLcB/s1600/Screen%2BShot%2B2017-03-02%2Bat%2B9.12.10%2BAM.png)

**Comment by mit-mit** [comment]
We may also need to reconsider our terminology; perhaps the term 'hot reload' is part of the problem ('reload' is system language, the developer is trying to view their changes, not trying to reload anything).

**Comment by devoncarew** [comment]
Some work for this landed - additional changes will be tracked in more specific issues.
