### ISSUE TITLE
Insufficient warning when the build function doesn't return a widget

### ISSUE THREAD

**Issue by InMatrix** [flutter/flutter-intellij#808]
## Steps to Reproduce

I observed that a user omitted "return" before the widget defined in the build function and IJ didn't complain until the code was run. 

To reproduce, remove "return" from "return new Scaffold(" from the starter app. You will only get a very subtle indicator (the lightblue bar left to the line in question) to show you a suggestion to fix it. 

![image](https://cloud.githubusercontent.com/assets/348942/23818838/175fd782-05b4-11e7-8861-2bb3d55a6700.png)

The Dart Analysis tab does show the error: 
![image](https://cloud.githubusercontent.com/assets/348942/23818864/5234370e-05b4-11e7-8d95-dbee42265293.png)

However, you won't notice this if you are on the console tab. There is no visual indicator to suggest there is new information in the Dart Analysis tab. Is it possible to change the appearance of the Dart Analysis tab when the user's attention is needed?

## Version info

That's the version used in the First Look event.

**Comment by devoncarew** [comment]
@pq, thoughts on bumping this up from a hint to a warning?

**Comment by pq** [comment]
@devoncarew : do you mean specifically for `build` methods?  If that's the case, I think we'd in fact be adding a new error code (which sounds good FWIW).  Otherwise, if you mean bumping that error in the general case I suppose we run the risk of causing some unwanted noise.

Happy to explore either way. 👍

**Comment by pq** [comment]
FYI @bwilkerson, here's the scenario I was describing.  It looks like `MISSING_RETURN` is a hint.  I wonder, in general, if this shouldn't be a warning?

**Comment by bwilkerson** [comment]
I'm still hesitant to promote hints to warnings by default because warnings are specified in the spec. We could promote it by default for Flutter by adding it to the default analysis options file.

But I think the OP is right that it makes sense to (a) do a better job of displaying hints in the editor and / or (b) make it more obvious when the content of the "Dart Analysis" view has changed and should be looked at.

**Comment by mit-mit** [comment]
I like prompting this for Flutter. Seems consistent with how we prompted missing required parameters.

**Comment by pq** [comment]
@mit-mit : as it stands we would be escalating this error for _all_ missing returns (not just `build` implementers).  Does that sound right?

**Comment by devoncarew** [comment]
Yup, this does escalate for all missing returns. I think that's ok? I don't see any missing returns in the flutter codebase, so suspect we won't see a lot of unexpected noise from increasing the severity on this.

**Comment by pq** [comment]
Looks like the plan of action is to bump this error code in flutter tools.  I can take a look at that.

**Comment by InMatrix** [comment]
Thanks for making the improvement!
