### ISSUE TITLE
fix and re-enable launching in profile (and release) mode(s)

### ISSUE THREAD

**Issue by mit-mit** [flutter/flutter-intellij#930]
M13 RC on macOS: Run -> Flutter Run (Profile) fails on a Nexus 5X with:

```
Launching lib/main.dart on Nexus 5X in profile mode...
Built build/app/outputs/apk/app-profile.apk (9.1MB).
F/libc    (22085): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5c in tid 22103 (ui_thread)
Application finished.
```

`flutter run --profile` against the same device succeeds.

**Comment by devoncarew** [comment]
note: we should add more logging to the Flutter plugin so that in cases like these, we can ask for the user's IntelliJ logs to help diagnose

**Comment by pq** [comment]
Repro'ed locally.  Confirmed `flutter run --machine --profile` works from the shell.

**Comment by pq** [comment]
**Quick update.**  After some spelunking, this line in `DartVmServiceDebugProcessZ#connect` ultimately triggers the unhappy state:

    myVmServiceWrapper.handleDebuggerConnected();

Removing it allows the profile run to work.

It looks like we need to add some awareness to the `DartVmServiceDebugProcessZ` of what mode we're running in so that we can be smart about not connecting the debugger in the profile case.  (We'll also want to disable the reload and restart icons.)  Since this is a bit involved, I'll back out the menu contributions pending a proper fix lest we hold up the release.

**Comment by devoncarew** [comment]
Seems like this is largely about plumbing the data through; what's the likely ETA of a fix? I'd prefer not to plan for a dot release if we know about the issues ahead of time.

**Comment by pq** [comment]
It may not require a ton of plumbing depending on how early we can short-circuit.  Requires some investigation though.

**Comment by devoncarew** [comment]
I did some investigation here: looks like in addition to disabling the call to `scheduleConnectNew()`, we'd need to do some work to enable the observatory button when running in `--profile` mode. Unlikely to get this done for this release -

**Comment by devoncarew** [comment]
(bumping this issue to the next milestone)
