### ISSUE TITLE
Unable to resolve imports from Android Support Repository

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter-intellij#966]
I used the Android SDK Manager to install the Android Support Repository. When I now try to import something from there (e.g. `android.support.v4.content.LocalBroadcastManager`) into the Android app of my Flutter app, IntelliJ is unable to resolve it:

```
Cannot resolve Symbol 'LocalBroadcastManager'
```

The app compiles just fine with that import though. I played around a little with the "Project Structure..." settings, but without much success. It seems like there is no jar for the Android Support Repository on disk that I can include.

Would be nice to document how you can add and use stuff from the Android SDK with the new "Editing Android code in IntelliJ IDEA" support in IntelliJ with Flutter.

**Comment by skybrian** [comment]
Hmm... I'm not up to speed on this yet, but the build is actually done using Gradle. In the build, the support libraries are defined in android/app/src/build.gradle.

If you can figure out where Gradle puts its output, maybe get the jar from there?

**Comment by skybrian** [comment]
Android support files seem to be installed here: $ANDROID_HOME/extras/android/m2repository. As the name suggests, these are Maven repository files.

It looks like LocalBroadcastManager is here:

```
$ ls $ANDROD_HOME/extras/android/m2repository/com/android/support/support-v4/25.3.1
support-v4-25.3.1.aar
support-v4-25.3.1.aar.md5
support-v4-25.3.1.aar.sha1
support-v4-25.3.1.pom
support-v4-25.3.1.pom.md5
support-v4-25.3.1.pom.sha1
```
An aar file is a zip file in Android Archive Format. If you look inside it there is classes.jar

Based on Stack Overflow, it's apparently possible to unzip it and add the .jar file directly, but the normal way to do this is using Gradle.

**Comment by skybrian** [comment]
To add the dependency to your Gradle build, you need to add something like this to the `dependencies` clause in android/app/build.gradle:

```
    compile 'com.android.support:appcompat-v7:25.3.1'
```

**Comment by skybrian** [comment]
It looks like if you add that line and then build with "flutter run", it puts all the jars below this directory:

```
build/app/intermediates/exploded-aar
```

To determine which jar it is:

```
find build/app/intermediates/exploded-aar -name '*.jar' | xargs grep LocalBroadcastManager
Binary file build/app/intermediates/exploded-aar/com.android.support/support-core-utils/25.3.1/jars/classes.jar matches
```

I created a project library named `exploded-aar` and added this jar file, and it seems to have done the trick.

**Comment by jakobr-google** [comment]
I tried to reproduce this, and I think the issue is with how we set up the projects, as well as a little hiccup with Android dependencies.

Here's what I did:

* `flutter create foo`
* Open `foo/android` in IDEA. Let it import the project from Gradle.
* Added `compile 'com.android.support:support-v4:25.3.1' dependency in `android/app/build.gradle`.

At this point, I would normally expect a Gradle sync in IDEA to pick up the added dependency and just work, but it didn't. I actually had to

* Build -> Build Project

After that, `LocalBroadcastManager` (and whatever else I wanted from support) was available in IDEA.

So, looks like the Android dependencies are fetched from the `android/build` directory, since `LocalBroadcastManager` stopped working in the IDE when I removed that directory.

I don't think we should try to work around this, and if we do, it should only be temporary until this issue is fixed upstream.

Also note that I didn't open `foo/` in IDEA. That project doesn't look like it's set up correctly for native Android development. In particular, it doesn't look like it uses Gradle, and it didn't pick up the new dependency even after I'd built the project.

**Comment by skybrian** [comment]
re: "foo/android in IDEA. Let it import the project from Gradle"

Yes, this turns on Gradle integration. However, you don't have a Flutter project! In particular you don't have hot reload, etc.

If you create a Flutter project in the normal way, we are not setting up Gradle integration at all. An "android" module is added which is really just a Java module with the SDK set to an Android SDK. Setting the Java classpath as well will allow more imports to be resolved.

So far I haven't managed to get Gradle integration and Flutter integration going at the same time. If you figure it out, we can see if we can do it automatically by changing the "flutter create" templates.

**Comment by Crazywater** [comment]
Just to understand the scope correctly: This effectively means no IDE support for Java code in Flutter projects, correct? (except for built-in types)

Seems like the directory build/app/intermediates/exploded-aar also doesn't exist anymore.

**Comment by stevemessick** [comment]
To address the original request, see:
https://github.com/flutter/flutter-intellij/blob/master/docs/android.md

**Comment by stevemessick** [comment]
Fixed with https://github.com/flutter/flutter-intellij/pull/1782

**Comment by bincyvenugopal** [comment]
i couldnt import these :
import com.github.mikephil.charting.animation.Easing;
import com.github.mikephil.charting.charts.PieChart;
import com.github.mikephil.charting.components.Legend;
import com.github.mikephil.charting.data.PieData;
import com.github.mikephil.charting.data.PieDataSet;
import com.github.mikephil.charting.data.PieEntry;
import com.github.mikephil.charting.utils.ColorTemplate;
