### ISSUE TITLE
publish M13.1

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#977]
Mostly an FYI:

We're thinking of doing a patch release (M13.1) to capture:

- the fix for https://github.com/flutter/flutter-intellij/issues/947
- improvements to the progress display when creating new projects

Given how much code changed for the 2nd item, this may mean a whole push from master.

/cc @skybrian, who did the work for the 2nd item

**Comment by devoncarew** [comment]
@pq, I think we're good to go!

/cc @skybrian @mit-mit

**Comment by pq** [comment]
Tagged: https://github.com/flutter/flutter-intellij/releases/tag/13.1
Released: https://plugins.jetbrains.com/plugin/9212-flutter/update/34818

🤘

**Comment by mit-mit** [comment]
Thanks, looked good on my testing also!

On May 4, 2017 18:59, "Phil Quitslund" <notifications@github.com> wrote:

Closed #977 <https://github.com/flutter/flutter-intellij/issues/977>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/flutter/flutter-intellij/issues/977#event-1069304722>,
or mute the thread
