### ISSUE TITLE
Project not recognized as a flutter project

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter-intellij#997]
I manually created a run configuration, pointing it to "lib/main.dart". I have the Android Emulator running. The command-line "flutter run" can run my app. But, in IntelliJ, the run button is disabled:

![capture9](https://cloud.githubusercontent.com/assets/5479/25775749/70735cde-3261-11e7-9873-29762efb912b.PNG)

I just installed IntelliJ CE (2017.1.2) and the latest Flutter (13.1) and Dart plugins (171.4424).

What do I need to do/configure so I can launch from IntelliJ? Thanks!

**Comment by devoncarew** [comment]
In your toolbar, there is no device selector (or hot reload button). This tells me that `myflutterapp` isn't seen as a flutter project. Not clear why that is. In order to trouble shoot, can you:

- see if `Tools > Flutter > Flutter Doctor` is available and runs? (or, `Tools > Flutter > Submit Feedback`)
- open the settings, and see if there's a flutter sdk set in `Languages & Frameworks > Flutter`
- try re-starting IntelliJ
- run `flutter doctor` from the cli and past it here (w/ an eye towards validating the IntelliJ sections)

Thanks!

**Comment by sethladd** [comment]
Sure, I'll try to do this when I get home.

I'm not sure I did anything weird. This was from 'flutter create myflutterapp' and then I opened this app from the initial splash screen of IntelliJ.

**Comment by mit-mit** [comment]
Closing as stale (there have been no other similar reports either).
